export const INDUSTRIES = [
  "Công nghệ thông tin",
  "Marketing & Quảng cáo",
  "Tài chính & Ngân hàng",
  "Kinh doanh & Bán hàng",
  "Quản trị nhân sự",
  "Chăm sóc khách hàng",
  "Thiết kế & Nghệ thuật",
  "Kế toán & Kiểm toán",
  "Quản lý sản phẩm",
  "Giáo dục & Đào tạo",
  "Y tế & Dược phẩm",
  "Luật & Pháp lý",
  "Xây dựng & Bất động sản",
  "Du lịch & Nhà hàng - Khách sạn",
  "Khác",
];

export const PREDEFINED_QUESTIONS = [
  "Chào mừng bạn đến với buổi phỏng vấn giả lập của InterV! Hãy giới thiệu ngắn gọn về bản thân, kinh nghiệm làm việc và lý do tại sao bạn quan tâm đến lĩnh vực này?",
  "Cảm ơn phần giới thiệu của bạn. Tiếp theo, hãy chia sẻ về một dự án hoặc một vấn đề kỹ thuật phức tạp nhất mà bạn đã từng giải quyết. Bạn đã áp dụng giải pháp nào và kết quả cụ thể ra sao?",
  "Thật thú vị. Để kết thúc buổi phỏng vấn hôm nay, bạn có thể chia sẻ về một lần bạn xảy ra bất đồng ý kiến với đồng nghiệp hoặc cấp trên trong công việc không? Bạn đã giải quyết nó như thế nào?",
];

export const RECHARGE_PACKAGES = [
  { amount: 10000, credit: 100, bonus: 0 },
  { amount: 20000, credit: 200, bonus: 10 },
  { amount: 50000, credit: 500, bonus: 40 },
  { amount: 100000, credit: 1000, bonus: 100 },
  { amount: 200000, credit: 2000, bonus: 250 },
  { amount: 500000, credit: 5000, bonus: 750 },
];

export const SOCIAL_PLATFORMS = [
  { id: "facebook", name: "Facebook", placeholder: "username..." },
  { id: "instagram", name: "Instagram", placeholder: "username..." },
  { id: "tiktok", name: "TikTok", placeholder: "username..." },
  { id: "linkedin", name: "LinkedIn", placeholder: "username..." },
  { id: "github", name: "GitHub", placeholder: "username..." },
  { id: "leetcode", name: "LeetCode", placeholder: "username..." },
  { id: "x", name: "X", placeholder: "username..." },
];

import { DifficultyLevel, AiPersonality } from "../types";

const DEFAULT_DIFFICULTY_LEVELS: DifficultyLevel[] = [
  { id: "Junior", name: "Junior", description: "Kỹ năng nền tảng" },
  { id: "Middle", name: "Middle", description: "Giải quyết độc lập" },
  { id: "Senior", name: "Senior", description: "Kỹ năng nâng cao & Quản lý" },
  { id: "Lead", name: "Lead", description: "Định hướng & Lãnh đạo" },
];

const DEFAULT_AI_PERSONALITIES: AiPersonality[] = [
  {
    id: "elena",
    name: "Elena (Friendly)",
    role: "HR Manager",
    description: "Dịu dàng, động viên, tập trung khai thác kỹ năng mềm và khả năng thích nghi văn hóa.",
    avatarBg: "from-pink-500/20 to-rose-500/20 border-rose-500/30",
    avatarColor: "text-rose-400",
    introPrefix: "Chào bạn, mình là Elena từ ban nhân sự. Rất vui được đồng hành cùng bạn trong buổi phỏng vấn ngày hôm nay.",
  },
  {
    id: "marcus",
    name: "Marcus (Strict)",
    role: "Project Director",
    description: "Nghiêm khắc, chuyên nghiệp, đặt câu hỏi hóc búa và đi thẳng trực diện vào vấn đề.",
    avatarBg: "from-amber-500/20 to-red-500/20 border-red-500/30",
    avatarColor: "text-red-400",
    introPrefix: "Chào anh/chị. Tôi là Marcus. Hôm nay tôi sẽ trực tiếp đánh giá năng lực của anh/chị. Hãy đi thẳng vào câu hỏi.",
  },
];

export const DIFFICULTY_LEVELS_BY_INDUSTRY: Record<string, DifficultyLevel[]> = {
  "Công nghệ thông tin": [
    { id: "Junior", name: "Junior", description: "Kỹ năng nền tảng" },
    { id: "Middle", name: "Middle", description: "Giải quyết độc lập" },
    { id: "Senior", name: "Senior", description: "Thiết kế hệ thống" },
    { id: "Lead", name: "Lead", description: "Quản lý & Định hướng" },
  ],
  "Marketing & Quảng cáo": [
    { id: "Intern", name: "Intern", description: "Thực tập sinh" },
    { id: "Executive", name: "Executive", description: "Triển khai chiến dịch" },
    { id: "Leader", name: "Leader", description: "Quản lý nhóm Marketing" },
    { id: "Manager", name: "Manager", description: "Xây dựng chiến lược" },
  ],
  "Tài chính & Ngân hàng": [
    { id: "Analyst", name: "Analyst", description: "Phân tích số liệu" },
    { id: "Specialist", name: "Specialist", description: "Kiểm soát rủi ro" },
    { id: "Manager", name: "Manager", description: "Hoạch định tài chính" },
    { id: "Director", name: "Director", description: "Chiến lược vốn & Đầu tư" },
  ],
  "Kế toán & Kiểm toán": [
    { id: "Analyst", name: "Analyst", description: "Phân tích nghiệp vụ" },
    { id: "Specialist", name: "Specialist", description: "Kiểm soát số liệu" },
    { id: "Manager", name: "Manager", description: "Hoạch định kế toán" },
    { id: "Director", name: "Director", description: "Chiến lược kiểm toán" },
  ],
  "Kinh doanh & Bán hàng": [
    { id: "Executive", name: "Executive", description: "Khai thác thị trường" },
    { id: "Specialist", name: "Specialist", description: "Chăm sóc khách hàng VIP" },
    { id: "Leader", name: "Leader", description: "Quản lý doanh số & Team" },
    { id: "Manager", name: "Manager", description: "Phát triển đối tác" },
  ],
  "Chăm sóc khách hàng": [
    { id: "Executive", name: "Executive", description: "Hỗ trợ khách hàng sơ cấp" },
    { id: "Specialist", name: "Specialist", description: "Giải quyết khiếu nại" },
    { id: "Leader", name: "Leader", description: "Quản lý nhóm CSKH" },
    { id: "Manager", name: "Manager", description: "Chiến lược trải nghiệm" },
  ],
  "Quản lý sản phẩm": [
    { id: "Associate", name: "Associate", description: "Quản lý tính năng" },
    { id: "Product Owner", name: "Product Owner", description: "Định hình sản phẩm" },
    { id: "Senior PM", name: "Senior PM", description: "Chiến lược Go-To-Market" },
    { id: "Director", name: "Director", description: "Quản lý danh mục sản phẩm" },
  ],
  "Quản trị nhân sự": [
    { id: "Intern/Assistant", name: "Intern/Assistant", description: "Tuyển dụng cơ bản" },
    { id: "Specialist", name: "Specialist", description: "Vận hành C&B, Quan hệ lao động" },
    { id: "Leader/Supervisor", name: "Leader/Supervisor", description: "Quản lý nhóm nhân sự" },
    { id: "Manager/HRBP", name: "Manager/HRBP", description: "Chiến lược nhân sự" },
  ],
  "Thiết kế & Nghệ thuật": [
    { id: "Junior Designer", name: "Junior Designer", description: "Thực thi thiết kế" },
    { id: "Senior Designer", name: "Senior Designer", description: "Tự chủ concept & Art" },
    { id: "Design Lead", name: "Design Lead", description: "Quản lý chất lượng & Đội ngũ" },
    { id: "Creative Director", name: "Creative Director", description: "Định hình thương hiệu & Concept" },
  ],
  "Giáo dục & Đào tạo": [
    { id: "Teacher/Tutor", name: "Teacher/Tutor", description: "Giảng dạy & Quản lý lớp" },
    { id: "Coordinator", name: "Coordinator", description: "Điều phối chuyên môn" },
    { id: "Academic Manager", name: "Academic Manager", description: "Đào tạo & Phát triển chương trình" },
    { id: "Education Director", name: "Education Director", description: "Định hướng & Vận hành giáo dục" },
  ],
  "Y tế & Dược phẩm": [
    { id: "Practitioner/Pharmacist", name: "Practitioner/Pharmacist", description: "Tư vấn & Chăm sóc cơ bản" },
    { id: "Specialist", name: "Specialist", description: "Chẩn đoán & Điều trị chuyên sâu" },
    { id: "Chief Pharmacist/Head Doctor", name: "Chief Pharmacist/Head Doctor", description: "Quản lý khoa/Nhà thuốc" },
    { id: "Medical Director", name: "Medical Director", description: "An toàn & Quản lý chất lượng y tế" },
  ],
  "Luật & Pháp lý": [
    { id: "Legal Assistant", name: "Legal Assistant", description: "Hỗ trợ nghiên cứu & Soạn thảo" },
    { id: "Legal Counsel", name: "Legal Counsel", description: "Tư vấn & Giải quyết tranh chấp" },
    { id: "Senior Counsel", name: "Senior Counsel", description: "Chiến lược pháp lý doanh nghiệp" },
    { id: "Legal Director/Partner", name: "Legal Director/Partner", description: "Đại diện pháp luật & Quản trị rủi ro" },
  ],
  "Xây dựng & Bất động sản": [
    { id: "Site Engineer/Agent", name: "Site Engineer/Agent", description: "Giám sát thi công/Tư vấn bán hàng" },
    { id: "Project Engineer/Consultant", name: "Project Engineer/Consultant", description: "Quản lý tiến độ/Thẩm định dự án" },
    { id: "Project Manager/Head", name: "Project Manager/Head", description: "Chỉ huy trưởng/Quản lý dự án" },
    { id: "Project Director", name: "Project Director", description: "Điều hành & Đấu thầu chuỗi dự án" },
  ],
  "Du lịch & Nhà hàng - Khách sạn": [
    { id: "Staff/Receptionist", name: "Staff/Receptionist", description: "Đón tiếp & Phục vụ trực tiếp" },
    { id: "Supervisor", name: "Supervisor", description: "Giám sát dịch vụ & Xử lý sự cố" },
    { id: "Department Manager", name: "Department Manager", description: "Quản lý bộ phận F&B/Front Office" },
    { id: "General Manager", name: "General Manager", description: "Điều hành toàn diện & Tối ưu doanh thu" },
  ],
  "Khác": [
    { id: "Junior", name: "Junior", description: "Kỹ năng nền tảng" },
    { id: "Middle", name: "Middle", description: "Giải quyết độc lập" },
    { id: "Senior", name: "Senior", description: "Kỹ năng nâng cao & Quản lý" },
    { id: "Lead", name: "Lead", description: "Định hướng & Lãnh đạo" },
  ],
};

export const AI_PERSONALITIES_BY_INDUSTRY: Record<string, AiPersonality[]> = {
  "Công nghệ thông tin": [
    {
      id: "sophia",
      name: "Sophia (Tech Lead)",
      role: "Technical Architect",
      description: "Sâu sắc, chuyên môn cao, đi sâu vào tư duy giải thuật, kiến trúc hệ thống và clean code.",
      avatarBg: "from-cyan-500/20 to-blue-500/20 border-blue-500/30",
      avatarColor: "text-cyan-400",
      introPrefix: "Chào bạn, mình là Sophia, Technical Lead. Hôm nay chúng ta sẽ trao đổi sâu hơn về mặt kỹ thuật và kiến trúc nhé.",
    },
    {
      id: "marcus",
      name: "Marcus (Strict)",
      role: "Project Director",
      description: "Nghiêm khắc, chuyên nghiệp, đặt câu hỏi hóc búa và đi thẳng trực diện vào vấn đề.",
      avatarBg: "from-amber-500/20 to-red-500/20 border-red-500/30",
      avatarColor: "text-red-400",
      introPrefix: "Chào anh/chị. Tôi là Marcus. Hôm nay tôi sẽ trực tiếp đánh giá năng lực của anh/chị. Hãy đi thẳng vào câu hỏi.",
    },
    {
      id: "elena",
      name: "Elena (Friendly)",
      role: "HR Manager",
      description: "Dịu dàng, động viên, tập trung khai thác kỹ năng mềm và khả năng thích nghi văn hóa.",
      avatarBg: "from-pink-500/20 to-rose-500/20 border-rose-500/30",
      avatarColor: "text-rose-400",
      introPrefix: "Chào bạn, mình là Elena từ ban nhân sự. Rất vui được đồng hành cùng bạn trong buổi phỏng vấn ngày hôm nay.",
    },
  ],
  "Marketing & Quảng cáo": [
    {
      id: "lucas",
      name: "Lucas (Creative)",
      role: "Creative Director",
      description: "Sáng tạo, am hiểu thị trường, tập trung vào tăng trưởng (Growth), chỉ số KPIs/ROI và thương hiệu.",
      avatarBg: "from-purple-500/20 to-indigo-500/20 border-indigo-500/30",
      avatarColor: "text-indigo-400",
      introPrefix: "Chào bạn, tôi là Lucas, Creative Director. Rất vui được gặp bạn để trao đổi về các ý tưởng sáng tạo và chiến lược marketing.",
    },
    {
      id: "elena",
      name: "Elena (Friendly)",
      role: "HR Manager",
      description: "Dịu dàng, động viên, tập trung khai thác kỹ năng mềm và khả năng thích nghi văn hóa.",
      avatarBg: "from-pink-500/20 to-rose-500/20 border-rose-500/30",
      avatarColor: "text-rose-400",
      introPrefix: "Chào bạn, mình là Elena từ ban nhân sự. Rất vui được đồng hành cùng bạn trong buổi phỏng vấn ngày hôm nay.",
    },
    {
      id: "marcus",
      name: "Marcus (Strict)",
      role: "Project Director",
      description: "Nghiêm khắc, chuyên nghiệp, đặt câu hỏi hóc búa và đi thẳng trực diện vào vấn đề.",
      avatarBg: "from-amber-500/20 to-red-500/20 border-red-500/30",
      avatarColor: "text-red-400",
      introPrefix: "Chào anh/chị. Tôi là Marcus. Hôm nay tôi sẽ trực tiếp đánh giá năng lực của anh/chị. Hãy đi thẳng vào câu hỏi.",
    },
  ],
  "Tài chính & Ngân hàng": [
    {
      id: "david",
      name: "David (Finance)",
      role: "Financial Controller",
      description: "Cẩn trọng, logic cao, đi sâu vào báo cáo tài chính, phân tích rủi ro và quản lý ngân sách.",
      avatarBg: "from-teal-500/20 to-emerald-500/20 border-emerald-500/30",
      avatarColor: "text-emerald-400",
      introPrefix: "Chào anh/chị. Tôi là David, Financial Controller. Buổi phỏng vấn hôm nay sẽ tập trung vào kỹ năng phân tích tài chính và quản trị rủi ro.",
    },
    {
      id: "marcus",
      name: "Marcus (Strict)",
      role: "Project Director",
      description: "Nghiêm khắc, chuyên nghiệp, đặt câu hỏi hóc búa và đi thẳng trực diện vào vấn đề.",
      avatarBg: "from-amber-500/20 to-red-500/20 border-red-500/30",
      avatarColor: "text-red-400",
      introPrefix: "Chào anh/chị. Tôi là Marcus. Hôm nay tôi sẽ trực tiếp đánh giá năng lực của anh/chị. Hãy đi thẳng vào câu hỏi.",
    },
    {
      id: "elena",
      name: "Elena (Friendly)",
      role: "HR Manager",
      description: "Dịu dàng, động viên, tập trung khai thác kỹ năng mềm và khả năng thích nghi văn hóa.",
      avatarBg: "from-pink-500/20 to-rose-500/20 border-rose-500/30",
      avatarColor: "text-rose-400",
      introPrefix: "Chào bạn, mình là Elena từ ban nhân sự. Rất vui được đồng hành cùng bạn trong buổi phỏng vấn ngày hôm nay.",
    },
  ],
  "Kế toán & Kiểm toán": [
    {
      id: "david",
      name: "David (Finance)",
      role: "Financial Controller",
      description: "Cẩn trọng, logic cao, đi sâu vào báo cáo tài chính, phân tích rủi ro và quản lý ngân sách.",
      avatarBg: "from-teal-500/20 to-emerald-500/20 border-emerald-500/30",
      avatarColor: "text-emerald-400",
      introPrefix: "Chào anh/chị. Tôi là David, Financial Controller. Buổi phỏng vấn hôm nay sẽ tập trung vào kỹ năng phân tích tài chính và quản trị rủi ro.",
    },
    {
      id: "marcus",
      name: "Marcus (Strict)",
      role: "Project Director",
      description: "Nghiêm khắc, chuyên nghiệp, đặt câu hỏi hóc búa và đi thẳng trực diện vào vấn đề.",
      avatarBg: "from-amber-500/20 to-red-500/20 border-red-500/30",
      avatarColor: "text-red-400",
      introPrefix: "Chào anh/chị. Tôi là Marcus. Hôm nay tôi sẽ trực tiếp đánh giá năng lực của anh/chị. Hãy đi thẳng vào câu hỏi.",
    },
    {
      id: "elena",
      name: "Elena (Friendly)",
      role: "HR Manager",
      description: "Dịu dàng, động viên, tập trung khai thác kỹ năng mềm và khả năng thích nghi văn hóa.",
      avatarBg: "from-pink-500/20 to-rose-500/20 border-rose-500/30",
      avatarColor: "text-rose-400",
      introPrefix: "Chào bạn, mình là Elena từ ban nhân sự. Rất vui được đồng hành cùng bạn trong buổi phỏng vấn ngày hôm nay.",
    },
  ],
  "Kinh doanh & Bán hàng": [
    {
      id: "olivia",
      name: "Olivia (Sales)",
      role: "Head of Sales",
      description: "Năng động, hướng tới kết quả, đi sâu vào kỹ năng đàm phán, xử lý từ chối và chốt hợp đồng.",
      avatarBg: "from-orange-500/20 to-amber-500/20 border-amber-500/30",
      avatarColor: "text-amber-400",
      introPrefix: "Chào bạn, tôi là Olivia. Hôm nay chúng ta sẽ trao đổi về các tình huống thực tế trong việc phát triển khách hàng và tối ưu doanh thu.",
    },
    {
      id: "elena",
      name: "Elena (Friendly)",
      role: "HR Manager",
      description: "Dịu dàng, động viên, tập trung khai thác kỹ năng mềm và khả năng thích nghi văn hóa.",
      avatarBg: "from-pink-500/20 to-rose-500/20 border-rose-500/30",
      avatarColor: "text-rose-400",
      introPrefix: "Chào bạn, mình là Elena từ ban nhân sự. Rất vui được đồng hành cùng bạn trong buổi phỏng vấn ngày hôm nay.",
    },
    {
      id: "marcus",
      name: "Marcus (Strict)",
      role: "Project Director",
      description: "Nghiêm khắc, chuyên nghiệp, đặt câu hỏi hóc búa và đi thẳng trực diện vào vấn đề.",
      avatarBg: "from-amber-500/20 to-red-500/20 border-red-500/30",
      avatarColor: "text-red-400",
      introPrefix: "Chào anh/chị. Tôi là Marcus. Hôm nay tôi sẽ trực tiếp đánh giá năng lực của anh/chị. Hãy đi thẳng vào câu hỏi.",
    },
  ],
  "Chăm sóc khách hàng": [
    {
      id: "olivia",
      name: "Olivia (CS Manager)",
      role: "Head of Support",
      description: "Thấu hiểu, chuyên nghiệp, tập trung vào sự hài lòng của khách hàng và giải quyết tình huống khẩn cấp.",
      avatarBg: "from-orange-500/20 to-amber-500/20 border-amber-500/30",
      avatarColor: "text-amber-400",
      introPrefix: "Chào bạn, tôi là Olivia. Hôm nay chúng ta sẽ kiểm tra các kịch bản hỗ trợ khách hàng thực tế và cách tối ưu trải nghiệm người dùng.",
    },
    {
      id: "elena",
      name: "Elena (Friendly)",
      role: "HR Manager",
      description: "Dịu dàng, động viên, tập trung khai thác kỹ năng mềm và khả năng thích nghi văn hóa.",
      avatarBg: "from-pink-500/20 to-rose-500/20 border-rose-500/30",
      avatarColor: "text-rose-400",
      introPrefix: "Chào bạn, mình là Elena từ ban nhân sự. Rất vui được đồng hành cùng bạn trong buổi phỏng vấn ngày hôm nay.",
    },
    {
      id: "marcus",
      name: "Marcus (Strict)",
      role: "Project Director",
      description: "Nghiêm khắc, chuyên nghiệp, đặt câu hỏi hóc búa và đi thẳng trực diện vào vấn đề.",
      avatarBg: "from-amber-500/20 to-red-500/20 border-red-500/30",
      avatarColor: "text-red-400",
      introPrefix: "Chào anh/chị. Tôi là Marcus. Hôm nay tôi sẽ trực tiếp đánh giá năng lực của anh/chị. Hãy đi thẳng vào câu hỏi.",
    },
  ],
  "Quản lý sản phẩm": [
    {
      id: "sophia",
      name: "Sophia (Tech PM)",
      role: "Product Lead",
      description: "Sâu sắc, chú trọng roadmap, định hình sản phẩm dựa trên dữ liệu và bài toán thị trường.",
      avatarBg: "from-cyan-500/20 to-blue-500/20 border-blue-500/30",
      avatarColor: "text-cyan-400",
      introPrefix: "Chào bạn, mình là Sophia, Product Lead. Hôm nay chúng ta sẽ thảo luận về chiến lược sản phẩm và cách ưu tiên các tính năng cốt lõi.",
    },
    {
      id: "lucas",
      name: "Lucas (Creative)",
      role: "Creative Director",
      description: "Sáng tạo, am hiểu thị trường, tập trung vào tăng trưởng (Growth), chỉ số KPIs/ROI và thương hiệu.",
      avatarBg: "from-purple-500/20 to-indigo-500/20 border-indigo-500/30",
      avatarColor: "text-indigo-400",
      introPrefix: "Chào bạn, tôi là Lucas, Creative Director. Rất vui được gặp bạn để trao đổi về các ý tưởng sáng tạo và chiến lược marketing.",
    },
    {
      id: "elena",
      name: "Elena (Friendly)",
      role: "HR Manager",
      description: "Dịu dàng, động viên, tập trung khai thác kỹ năng mềm và khả năng thích nghi văn hóa.",
      avatarBg: "from-pink-500/20 to-rose-500/20 border-rose-500/30",
      avatarColor: "text-rose-400",
      introPrefix: "Chào bạn, mình là Elena từ ban nhân sự. Rất vui được đồng hành cùng bạn trong buổi phỏng vấn ngày hôm nay.",
    },
  ],
  "Quản trị nhân sự": [
    {
      id: "harvey",
      name: "Harvey (Professional)",
      role: "HR Director",
      description: "Chuyên nghiệp, nhạy bén, đặt câu hỏi về luật lao động, giữ chân nhân tài và văn hóa doanh nghiệp.",
      avatarBg: "from-blue-500/20 to-indigo-500/20 border-indigo-500/30",
      avatarColor: "text-indigo-400",
      introPrefix: "Chào bạn. Tôi là Harvey, Giám đốc Nhân sự. Chúng ta sẽ cùng thảo luận về cách tối ưu hóa nguồn lực con người nhé.",
    },
    {
      id: "elena",
      name: "Elena (Friendly)",
      role: "HR Manager",
      description: "Dịu dàng, động viên, tập trung khai thác kỹ năng mềm và khả năng thích nghi văn hóa.",
      avatarBg: "from-pink-500/20 to-rose-500/20 border-rose-500/30",
      avatarColor: "text-rose-400",
      introPrefix: "Chào bạn, mình là Elena từ ban nhân sự. Rất vui được đồng hành cùng bạn trong buổi phỏng vấn ngày hôm nay.",
    },
    {
      id: "marcus",
      name: "Marcus (Strict)",
      role: "Project Director",
      description: "Nghiêm khắc, chuyên nghiệp, đặt câu hỏi hóc búa và đi thẳng trực diện vào vấn đề.",
      avatarBg: "from-amber-500/20 to-red-500/20 border-red-500/30",
      avatarColor: "text-red-400",
      introPrefix: "Chào anh/chị. Tôi là Marcus. Hôm nay tôi sẽ trực tiếp đánh giá năng lực của anh/chị. Hãy đi thẳng vào câu hỏi.",
    },
  ],
  "Thiết kế & Nghệ thuật": [
    {
      id: "chloe",
      name: "Chloe (Artistic)",
      role: "Art Director",
      description: "Tập trung vào tư duy thẩm mỹ, quy trình sáng tạo, portfolio và khả năng giải quyết bài toán UX.",
      avatarBg: "from-fuchsia-500/20 to-pink-500/20 border-pink-500/30",
      avatarColor: "text-pink-400",
      introPrefix: "Hi bạn! Mình là Chloe, Art Director. Rất vui được thảo luận về các tác phẩm và tư duy sáng tạo của bạn.",
    },
    {
      id: "elena",
      name: "Elena (Friendly)",
      role: "HR Manager",
      description: "Dịu dàng, động viên, tập trung khai thác kỹ năng mềm và khả năng thích nghi văn hóa.",
      avatarBg: "from-pink-500/20 to-rose-500/20 border-rose-500/30",
      avatarColor: "text-rose-400",
      introPrefix: "Chào bạn, mình là Elena từ ban nhân sự. Rất vui được đồng hành cùng bạn trong buổi phỏng vấn ngày hôm nay.",
    },
    {
      id: "marcus",
      name: "Marcus (Strict)",
      role: "Project Director",
      description: "Nghiêm khắc, chuyên nghiệp, đặt câu hỏi hóc búa và đi thẳng trực diện vào vấn đề.",
      avatarBg: "from-amber-500/20 to-red-500/20 border-red-500/30",
      avatarColor: "text-red-400",
      introPrefix: "Chào anh/chị. Tôi là Marcus. Hôm nay tôi sẽ trực tiếp đánh giá năng lực của anh/chị. Hãy đi thẳng vào câu hỏi.",
    },
  ],
  "Giáo dục & Đào tạo": [
    {
      id: "mr_viet",
      name: "Thầy Việt (Pedagogical)",
      role: "Academic Dean",
      description: "Chuyên nghiệp, chú trọng phương pháp sư phạm, tâm lý học sinh và soạn giáo án.",
      avatarBg: "from-green-500/20 to-teal-500/20 border-teal-500/30",
      avatarColor: "text-teal-400",
      introPrefix: "Chào thầy/cô. Tôi là Việt, Trưởng phòng Đào tạo. Rất vui được trao đổi về chuyên môn sư phạm hôm nay.",
    },
    {
      id: "elena",
      name: "Elena (Friendly)",
      role: "HR Manager",
      description: "Dịu dàng, động viên, tập trung khai thác kỹ năng mềm và khả năng thích nghi văn hóa.",
      avatarBg: "from-pink-500/20 to-rose-500/20 border-rose-500/30",
      avatarColor: "text-rose-400",
      introPrefix: "Chào bạn, mình là Elena từ ban nhân sự. Rất vui được đồng hành cùng bạn trong buổi phỏng vấn ngày hôm nay.",
    },
    {
      id: "marcus",
      name: "Marcus (Strict)",
      role: "Project Director",
      description: "Nghiêm khắc, chuyên nghiệp, đặt câu hỏi hóc búa và đi thẳng trực diện vào vấn đề.",
      avatarBg: "from-amber-500/20 to-red-500/20 border-red-500/30",
      avatarColor: "text-red-400",
      introPrefix: "Chào anh/chị. Tôi là Marcus. Hôm nay tôi sẽ trực tiếp đánh giá năng lực của anh/chị. Hãy đi thẳng vào câu hỏi.",
    },
  ],
  "Y tế & Dược phẩm": [
    {
      id: "dr_minh",
      name: "Bác sĩ Minh (Precise)",
      role: "Chief Medical Officer",
      description: "Kỹ lưỡng, nghiêm ngặt về quy trình y tế, an toàn người bệnh và đạo đức ngành y.",
      avatarBg: "from-sky-500/20 to-cyan-500/20 border-cyan-500/30",
      avatarColor: "text-sky-400",
      introPrefix: "Chào anh/chị. Tôi là Bác sĩ Minh, Giám đốc Y khoa. Chúng ta sẽ làm việc cụ thể về kỹ năng lâm sàng và an toàn y tế.",
    },
    {
      id: "elena",
      name: "Elena (Friendly)",
      role: "HR Manager",
      description: "Dịu dàng, động viên, tập trung khai thác kỹ năng mềm và khả năng thích nghi văn hóa.",
      avatarBg: "from-pink-500/20 to-rose-500/20 border-rose-500/30",
      avatarColor: "text-rose-400",
      introPrefix: "Chào bạn, mình là Elena từ ban nhân sự. Rất vui được đồng hành cùng bạn trong buổi phỏng vấn ngày hôm nay.",
    },
    {
      id: "marcus",
      name: "Marcus (Strict)",
      role: "Project Director",
      description: "Nghiêm khắc, chuyên nghiệp, đặt câu hỏi hóc búa và đi thẳng trực diện vào vấn đề.",
      avatarBg: "from-amber-500/20 to-red-500/20 border-red-500/30",
      avatarColor: "text-red-400",
      introPrefix: "Chào anh/chị. Tôi là Marcus. Hôm nay tôi sẽ trực tiếp đánh giá năng lực của anh/chị. Hãy đi thẳng vào câu hỏi.",
    },
  ],
  "Luật & Pháp lý": [
    {
      id: "lawyer_khanh",
      name: "Luật sư Khánh (Analytical)",
      role: "Senior Legal Partner",
      description: "Tập trung vào tính tuân thủ, phân tích rủi ro hợp đồng, luật doanh nghiệp và kỹ năng tranh tụng.",
      avatarBg: "from-slate-500/20 to-neutral-500/20 border-neutral-500/30",
      avatarColor: "text-slate-400",
      introPrefix: "Chào anh/chị. Tôi là Khánh, Luật sư Thành viên. Hôm nay chúng ta sẽ kiểm tra tính thực chiến pháp lý của anh/chị.",
    },
    {
      id: "marcus",
      name: "Marcus (Strict)",
      role: "Project Director",
      description: "Nghiêm khắc, chuyên nghiệp, đặt câu hỏi hóc búa và đi thẳng trực diện vào vấn đề.",
      avatarBg: "from-amber-500/20 to-red-500/20 border-red-500/30",
      avatarColor: "text-red-400",
      introPrefix: "Chào anh/chị. Tôi là Marcus. Hôm nay tôi sẽ trực tiếp đánh giá năng lực của anh/chị. Hãy đi thẳng vào câu hỏi.",
    },
    {
      id: "elena",
      name: "Elena (Friendly)",
      role: "HR Manager",
      description: "Dịu dàng, động viên, tập trung khai thác kỹ năng mềm và khả năng thích nghi văn hóa.",
      avatarBg: "from-pink-500/20 to-rose-500/20 border-rose-500/30",
      avatarColor: "text-rose-400",
      introPrefix: "Chào bạn, mình là Elena từ ban nhân sự. Rất vui được đồng hành cùng bạn trong buổi phỏng vấn ngày hôm nay.",
    },
  ],
  "Xây dựng & Bất động sản": [
    {
      id: "mr_hoang",
      name: "Anh Hoàng (Realistic)",
      role: "Construction Director",
      description: "Thực tế, coi trọng an toàn lao động, kiểm soát chi phí công trình và xử lý phát sinh tại công trường.",
      avatarBg: "from-amber-600/20 to-orange-600/20 border-orange-500/30",
      avatarColor: "text-orange-400",
      introPrefix: "Chào cậu. Tôi là Hoàng, Giám đốc Dự án. Chúng ta nói chuyện thực tế về tiến độ và quản lý nhà thầu phụ.",
    },
    {
      id: "marcus",
      name: "Marcus (Strict)",
      role: "Project Director",
      description: "Nghiêm khắc, chuyên nghiệp, đặt câu hỏi hóc búa và đi thẳng trực diện vào vấn đề.",
      avatarBg: "from-amber-500/20 to-red-500/20 border-red-500/30",
      avatarColor: "text-red-400",
      introPrefix: "Chào anh/chị. Tôi là Marcus. Hôm nay tôi sẽ trực tiếp đánh giá năng lực của anh/chị. Hãy đi thẳng vào câu hỏi.",
    },
    {
      id: "elena",
      name: "Elena (Friendly)",
      role: "HR Manager",
      description: "Dịu dàng, động viên, tập trung khai thác kỹ năng mềm và khả năng thích nghi văn hóa.",
      avatarBg: "from-pink-500/20 to-rose-500/20 border-rose-500/30",
      avatarColor: "text-rose-400",
      introPrefix: "Chào bạn, mình là Elena từ ban nhân sự. Rất vui được đồng hành cùng bạn trong buổi phỏng vấn ngày hôm nay.",
    },
  ],
  "Du lịch & Nhà hàng - Khách sạn": [
    {
      id: "ms_huong",
      name: "Chị Hương (Hospitable)",
      role: "General Manager",
      description: "Chú trọng tiêu chuẩn dịch vụ 5 sao, kỹ năng giao tiếp và khả năng xử lý phàn nàn của khách.",
      avatarBg: "from-yellow-500/20 to-amber-500/20 border-amber-500/30",
      avatarColor: "text-yellow-400",
      introPrefix: "Chào bạn. Tôi là Hương, Giám đốc Điều hành. Hôm nay chúng ta sẽ cùng trao đổi về dịch vụ khách hàng xuất sắc.",
    },
    {
      id: "elena",
      name: "Elena (Friendly)",
      role: "HR Manager",
      description: "Dịu dàng, động viên, tập trung khai thác kỹ năng mềm và khả năng thích nghi văn hóa.",
      avatarBg: "from-pink-500/20 to-rose-500/20 border-rose-500/30",
      avatarColor: "text-rose-400",
      introPrefix: "Chào bạn, mình là Elena từ ban nhân sự. Rất vui được đồng hành cùng bạn trong buổi phỏng vấn ngày hôm nay.",
    },
    {
      id: "marcus",
      name: "Marcus (Strict)",
      role: "Project Director",
      description: "Nghiêm khắc, chuyên nghiệp, đặt câu hỏi hóc búa và đi thẳng trực diện vào vấn đề.",
      avatarBg: "from-amber-500/20 to-red-500/20 border-red-500/30",
      avatarColor: "text-red-400",
      introPrefix: "Chào anh/chị. Tôi là Marcus. Hôm nay tôi sẽ trực tiếp đánh giá năng lực của anh/chị. Hãy đi thẳng vào câu hỏi.",
    },
  ],
  "Khác": [
    {
      id: "elena",
      name: "Elena (Friendly)",
      role: "HR Manager",
      description: "Dịu dàng, động viên, tập trung khai thác kỹ năng mềm và khả năng thích nghi văn hóa.",
      avatarBg: "from-pink-500/20 to-rose-500/20 border-rose-500/30",
      avatarColor: "text-rose-400",
      introPrefix: "Chào bạn, mình là Elena từ ban nhân sự. Rất vui được đồng hành cùng bạn trong buổi phỏng vấn ngày hôm nay.",
    },
    {
      id: "marcus",
      name: "Marcus (Strict)",
      role: "Project Director",
      description: "Nghiêm khắc, chuyên nghiệp, đặt câu hỏi hóc búa và đi thẳng trực diện vào vấn đề.",
      avatarBg: "from-amber-500/20 to-red-500/20 border-red-500/30",
      avatarColor: "text-red-400",
      introPrefix: "Chào anh/chị. Tôi là Marcus. Hôm nay tôi sẽ trực tiếp đánh giá năng lực của anh/chị. Hãy đi thẳng vào câu hỏi.",
    },
  ],
};

export function getDifficultyLevels(industry: string): DifficultyLevel[] {
  return DIFFICULTY_LEVELS_BY_INDUSTRY[industry] || DEFAULT_DIFFICULTY_LEVELS;
}

export function getAiPersonalities(industry: string): AiPersonality[] {
  return AI_PERSONALITIES_BY_INDUSTRY[industry] || DEFAULT_AI_PERSONALITIES;
}

export function getAiPersonality(id: string, industry: string): AiPersonality {
  const list = getAiPersonalities(industry);
  return list.find((a) => a.id === id) || list[0] || DEFAULT_AI_PERSONALITIES[0];
}
