# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import interv_ai_pb2 as interv__ai__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in interv_ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IntervAiStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/interv.ai.v1.IntervAi/Health',
                request_serializer=interv__ai__pb2.HealthRequest.SerializeToString,
                response_deserializer=interv__ai__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.ExtractJd = channel.unary_unary(
                '/interv.ai.v1.IntervAi/ExtractJd',
                request_serializer=interv__ai__pb2.JdExtractRequest.SerializeToString,
                response_deserializer=interv__ai__pb2.JdExtractResponse.FromString,
                _registered_method=True)
        self.ListVoices = channel.unary_unary(
                '/interv.ai.v1.IntervAi/ListVoices',
                request_serializer=interv__ai__pb2.ListVoicesRequest.SerializeToString,
                response_deserializer=interv__ai__pb2.ListVoicesResponse.FromString,
                _registered_method=True)
        self.SynthesizeTts = channel.unary_unary(
                '/interv.ai.v1.IntervAi/SynthesizeTts',
                request_serializer=interv__ai__pb2.TtsRequest.SerializeToString,
                response_deserializer=interv__ai__pb2.TtsResponse.FromString,
                _registered_method=True)
        self.StartInterview = channel.unary_unary(
                '/interv.ai.v1.IntervAi/StartInterview',
                request_serializer=interv__ai__pb2.InterviewStartRequest.SerializeToString,
                response_deserializer=interv__ai__pb2.InterviewStartResponse.FromString,
                _registered_method=True)
        self.GenerateOpeningTurn = channel.unary_unary(
                '/interv.ai.v1.IntervAi/GenerateOpeningTurn',
                request_serializer=interv__ai__pb2.InterviewOpeningRequest.SerializeToString,
                response_deserializer=interv__ai__pb2.InterviewTurnResponse.FromString,
                _registered_method=True)
        self.TranscribeAudio = channel.unary_unary(
                '/interv.ai.v1.IntervAi/TranscribeAudio',
                request_serializer=interv__ai__pb2.TranscribeAudioRequest.SerializeToString,
                response_deserializer=interv__ai__pb2.TranscribeAudioResponse.FromString,
                _registered_method=True)
        self.SubmitAnswer = channel.unary_unary(
                '/interv.ai.v1.IntervAi/SubmitAnswer',
                request_serializer=interv__ai__pb2.InterviewAnswerRequest.SerializeToString,
                response_deserializer=interv__ai__pb2.InterviewAnswerResponse.FromString,
                _registered_method=True)
        self.EvaluateInterview = channel.unary_unary(
                '/interv.ai.v1.IntervAi/EvaluateInterview',
                request_serializer=interv__ai__pb2.InterviewEvaluateRequest.SerializeToString,
                response_deserializer=interv__ai__pb2.InterviewEvaluateResponse.FromString,
                _registered_method=True)
        self.ExtractCandidateProfile = channel.unary_unary(
                '/interv.ai.v1.IntervAi/ExtractCandidateProfile',
                request_serializer=interv__ai__pb2.CandidateProfileRequest.SerializeToString,
                response_deserializer=interv__ai__pb2.CandidateProfileResponse.FromString,
                _registered_method=True)
        self.CreateStreamingToken = channel.unary_unary(
                '/interv.ai.v1.IntervAi/CreateStreamingToken',
                request_serializer=interv__ai__pb2.StreamingTokenRequest.SerializeToString,
                response_deserializer=interv__ai__pb2.StreamingTokenResponse.FromString,
                _registered_method=True)
        self.AnalyzeInterview = channel.stream_unary(
                '/interv.ai.v1.IntervAi/AnalyzeInterview',
                request_serializer=interv__ai__pb2.AudioAnalysisChunk.SerializeToString,
                response_deserializer=interv__ai__pb2.AudioAnalysisResponse.FromString,
                _registered_method=True)
        self.GetRagStatus = channel.unary_unary(
                '/interv.ai.v1.IntervAi/GetRagStatus',
                request_serializer=interv__ai__pb2.RagStatusRequest.SerializeToString,
                response_deserializer=interv__ai__pb2.RagStatusResponse.FromString,
                _registered_method=True)
        self.SearchKnowledge = channel.unary_unary(
                '/interv.ai.v1.IntervAi/SearchKnowledge',
                request_serializer=interv__ai__pb2.RagSearchRequest.SerializeToString,
                response_deserializer=interv__ai__pb2.RagSearchResponse.FromString,
                _registered_method=True)
        self.DeleteKnowledge = channel.unary_unary(
                '/interv.ai.v1.IntervAi/DeleteKnowledge',
                request_serializer=interv__ai__pb2.RagDeleteRequest.SerializeToString,
                response_deserializer=interv__ai__pb2.RagDeleteResponse.FromString,
                _registered_method=True)
        self.GetDeepSeekBalance = channel.unary_unary(
                '/interv.ai.v1.IntervAi/GetDeepSeekBalance',
                request_serializer=interv__ai__pb2.DeepSeekBalanceRequest.SerializeToString,
                response_deserializer=interv__ai__pb2.DeepSeekBalanceResponse.FromString,
                _registered_method=True)


class IntervAiServicer:
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractJd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVoices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SynthesizeTts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartInterview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateOpeningTurn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TranscribeAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitAnswer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluateInterview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractCandidateProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateStreamingToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeInterview(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRagStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchKnowledge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteKnowledge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeepSeekBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IntervAiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=interv__ai__pb2.HealthRequest.FromString,
                    response_serializer=interv__ai__pb2.HealthResponse.SerializeToString,
            ),
            'ExtractJd': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractJd,
                    request_deserializer=interv__ai__pb2.JdExtractRequest.FromString,
                    response_serializer=interv__ai__pb2.JdExtractResponse.SerializeToString,
            ),
            'ListVoices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVoices,
                    request_deserializer=interv__ai__pb2.ListVoicesRequest.FromString,
                    response_serializer=interv__ai__pb2.ListVoicesResponse.SerializeToString,
            ),
            'SynthesizeTts': grpc.unary_unary_rpc_method_handler(
                    servicer.SynthesizeTts,
                    request_deserializer=interv__ai__pb2.TtsRequest.FromString,
                    response_serializer=interv__ai__pb2.TtsResponse.SerializeToString,
            ),
            'StartInterview': grpc.unary_unary_rpc_method_handler(
                    servicer.StartInterview,
                    request_deserializer=interv__ai__pb2.InterviewStartRequest.FromString,
                    response_serializer=interv__ai__pb2.InterviewStartResponse.SerializeToString,
            ),
            'GenerateOpeningTurn': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateOpeningTurn,
                    request_deserializer=interv__ai__pb2.InterviewOpeningRequest.FromString,
                    response_serializer=interv__ai__pb2.InterviewTurnResponse.SerializeToString,
            ),
            'TranscribeAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.TranscribeAudio,
                    request_deserializer=interv__ai__pb2.TranscribeAudioRequest.FromString,
                    response_serializer=interv__ai__pb2.TranscribeAudioResponse.SerializeToString,
            ),
            'SubmitAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitAnswer,
                    request_deserializer=interv__ai__pb2.InterviewAnswerRequest.FromString,
                    response_serializer=interv__ai__pb2.InterviewAnswerResponse.SerializeToString,
            ),
            'EvaluateInterview': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateInterview,
                    request_deserializer=interv__ai__pb2.InterviewEvaluateRequest.FromString,
                    response_serializer=interv__ai__pb2.InterviewEvaluateResponse.SerializeToString,
            ),
            'ExtractCandidateProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractCandidateProfile,
                    request_deserializer=interv__ai__pb2.CandidateProfileRequest.FromString,
                    response_serializer=interv__ai__pb2.CandidateProfileResponse.SerializeToString,
            ),
            'CreateStreamingToken': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateStreamingToken,
                    request_deserializer=interv__ai__pb2.StreamingTokenRequest.FromString,
                    response_serializer=interv__ai__pb2.StreamingTokenResponse.SerializeToString,
            ),
            'AnalyzeInterview': grpc.stream_unary_rpc_method_handler(
                    servicer.AnalyzeInterview,
                    request_deserializer=interv__ai__pb2.AudioAnalysisChunk.FromString,
                    response_serializer=interv__ai__pb2.AudioAnalysisResponse.SerializeToString,
            ),
            'GetRagStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRagStatus,
                    request_deserializer=interv__ai__pb2.RagStatusRequest.FromString,
                    response_serializer=interv__ai__pb2.RagStatusResponse.SerializeToString,
            ),
            'SearchKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchKnowledge,
                    request_deserializer=interv__ai__pb2.RagSearchRequest.FromString,
                    response_serializer=interv__ai__pb2.RagSearchResponse.SerializeToString,
            ),
            'DeleteKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteKnowledge,
                    request_deserializer=interv__ai__pb2.RagDeleteRequest.FromString,
                    response_serializer=interv__ai__pb2.RagDeleteResponse.SerializeToString,
            ),
            'GetDeepSeekBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeepSeekBalance,
                    request_deserializer=interv__ai__pb2.DeepSeekBalanceRequest.FromString,
                    response_serializer=interv__ai__pb2.DeepSeekBalanceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'interv.ai.v1.IntervAi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('interv.ai.v1.IntervAi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IntervAi:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interv.ai.v1.IntervAi/Health',
            interv__ai__pb2.HealthRequest.SerializeToString,
            interv__ai__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractJd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interv.ai.v1.IntervAi/ExtractJd',
            interv__ai__pb2.JdExtractRequest.SerializeToString,
            interv__ai__pb2.JdExtractResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVoices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interv.ai.v1.IntervAi/ListVoices',
            interv__ai__pb2.ListVoicesRequest.SerializeToString,
            interv__ai__pb2.ListVoicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SynthesizeTts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interv.ai.v1.IntervAi/SynthesizeTts',
            interv__ai__pb2.TtsRequest.SerializeToString,
            interv__ai__pb2.TtsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartInterview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interv.ai.v1.IntervAi/StartInterview',
            interv__ai__pb2.InterviewStartRequest.SerializeToString,
            interv__ai__pb2.InterviewStartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateOpeningTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interv.ai.v1.IntervAi/GenerateOpeningTurn',
            interv__ai__pb2.InterviewOpeningRequest.SerializeToString,
            interv__ai__pb2.InterviewTurnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TranscribeAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interv.ai.v1.IntervAi/TranscribeAudio',
            interv__ai__pb2.TranscribeAudioRequest.SerializeToString,
            interv__ai__pb2.TranscribeAudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interv.ai.v1.IntervAi/SubmitAnswer',
            interv__ai__pb2.InterviewAnswerRequest.SerializeToString,
            interv__ai__pb2.InterviewAnswerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluateInterview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interv.ai.v1.IntervAi/EvaluateInterview',
            interv__ai__pb2.InterviewEvaluateRequest.SerializeToString,
            interv__ai__pb2.InterviewEvaluateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractCandidateProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interv.ai.v1.IntervAi/ExtractCandidateProfile',
            interv__ai__pb2.CandidateProfileRequest.SerializeToString,
            interv__ai__pb2.CandidateProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateStreamingToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interv.ai.v1.IntervAi/CreateStreamingToken',
            interv__ai__pb2.StreamingTokenRequest.SerializeToString,
            interv__ai__pb2.StreamingTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeInterview(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/interv.ai.v1.IntervAi/AnalyzeInterview',
            interv__ai__pb2.AudioAnalysisChunk.SerializeToString,
            interv__ai__pb2.AudioAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRagStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interv.ai.v1.IntervAi/GetRagStatus',
            interv__ai__pb2.RagStatusRequest.SerializeToString,
            interv__ai__pb2.RagStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interv.ai.v1.IntervAi/SearchKnowledge',
            interv__ai__pb2.RagSearchRequest.SerializeToString,
            interv__ai__pb2.RagSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interv.ai.v1.IntervAi/DeleteKnowledge',
            interv__ai__pb2.RagDeleteRequest.SerializeToString,
            interv__ai__pb2.RagDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeepSeekBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interv.ai.v1.IntervAi/GetDeepSeekBalance',
            interv__ai__pb2.DeepSeekBalanceRequest.SerializeToString,
            interv__ai__pb2.DeepSeekBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
