"""Vietnamese phonetic preparation for Vbee's Vietnamese voice.

The display question and the spoken question are separate values.  This module
only prepares the spoken value and contains the deterministic vocabulary used
when an English technical term reaches the TTS boundary.
"""

from __future__ import annotations

import re
from collections.abc import Iterable


PronunciationEntry = tuple[str, str]


# The same concept is often written as an acronym, a dotted package name, or a
# long form.  Keeping those aliases together makes the normalizer predictable.
PRONUNCIATION_SETS: dict[str, tuple[PronunciationEntry, ...]] = {
    "web_frontend": (
        ("React Native", "ri-ắc nây-tịp"), ("React JS", "ri-ác giây-ét"),
        ("React-JS", "ri-ác giây-ét"), ("ReactJS", "ri-ác giây-ét"),
        ("React.js", "ri-ác giây-ét"), ("React", "ri-ác"),
        ("Next.js", "néch giây ét"),
        ("NextJS", "néch giây ét"), ("Vue.js", "viu giây ét"),
        ("VueJS", "viu giây ét"), ("Nuxt.js", "nắc-stờ giây ét"),
        ("NuxtJS", "nắc-stờ giây ét"), ("AngularJS", "ang-giu-lờ giây ét"),
        ("Angular", "ang-giu-lờ"), ("SvelteKit", "sờ-velt kít"),
        ("Svelte", "sờ-velt"), ("Remix", "ri-mích"), ("Gatsby", "ghét-x-bi"),
        ("jQuery", "giây que-ri"), ("Tailwind CSS", "tâyl-wind xi ét ét"),
        ("Tailwind", "tâyl-wind"), ("Bootstrap", "buốt-strap"),
        ("Material UI", "mờ-ti-ri-ồ diu-ai"), ("Material-UI", "mờ-ti-ri-ồ diu-ai"),
        ("shadcn/ui", "shad xi en diu-ai"), ("Storybook", "sto-ri-búc"),
        ("WebAssembly", "web a-sem-bli"), ("WebGL", "web gi-ờ eo"),
        ("Three.js", "thờ-ri giây ét"), ("ThreeJS", "thờ-ri giây ét"),
        ("Electron", "i-léc-tron"), ("Progressive Web App", "pro-gre-sịp web ép"),
        ("PWA", "pi đắp-bồ-liu ây"), ("Single Page Application", "sing-gồ pây-chờ áp-li-kây-sần"),
        ("SPA", "ét pi ây"), ("Server-Side Rendering", "sơ-vờ sai-đ ren-đờ-ring"),
        ("SSR", "ét ét a"), ("Static Site Generation", "stát-tịc sait giê-nờ-rây-sần"),
        ("SSG", "ét ét gi"), ("Incremental Static Regeneration", "in-crờ-men-tồ stát-tịc ri-giê-nờ-rây-sần"),
        ("ISR", "ai ét a"), ("Client-Side Rendering", "cờ-lai-ần sai-đ ren-đờ-ring"),
        ("CSR", "xi ét a"), ("Document Object Model", "đóc-kiu-mần óp-giẹc mô-đồ"),
        ("DOM", "đom"), ("BOM", "bom"), ("Virtual DOM", "vơ-chuồ đom"),
        ("Shadow DOM", "sha-đô đom"), ("Web Components", "web cờm-pô-nần"),
        ("component", "cờm-pô-nần"), ("components", "cờm-pô-nần"),
        ("frontend", "phờ-rân-en"), ("front-end", "phờ-rân-en"),
        ("backend", "béc-en"), ("back-end", "béc-en"), ("full stack", "ful stác"),
        ("full-stack", "ful stác"), ("responsive", "ri-spon-sịp"),
        ("accessibility", "ắc-xe-si-bi-li-ti"), ("a11y", "ây-lờ-lờ-y"),
        ("user interface", "du-zờ in-tờ-phây-sờ"),
        ("user experience", "du-zờ ích-xpi-ri-ần-sờ"), ("UI", "diu-ai"),
        ("UX", "diu-ích"), ("SEO", "ét-i-ô"), ("Figma", "phích-mờ"),
        ("Redux", "ri-đắc"), ("Zustand", "du-xtan"),
        ("framework", "phờ-râym-quớc"), ("library", "lai-bờ-re-ri"),
        ("wireframe", "waiờ-phờ-râym"), ("prototype", "prô-tờ-taip"),
        ("design system", "đi-zain sí-stầm"), ("design token", "đi-zain tô-kần"),
    ),
    "languages_runtimes": (
        ("JavaScript", "gia-va-sờ-cờ-ríp"), ("TypeScript", "tai-pờ-sờ-cờ-ríp"),
        ("CoffeeScript", "co-phi-sờ-cờ-ríp"), ("ActionScript", "ắc-sần-sờ-cờ-ríp"),
        ("C Sharp", "xi sharp"), ("C#", "xi sharp"), ("C Plus Plus", "xi plớt plớt"),
        ("C++", "xi plớt plớt"), ("Objective-C", "óp-giẹc-tịp xi"),
        ("Visual Basic", "vi-giu-ồ bâ-sịc"), ("VB.NET", "vi-bi nét"),
        ("Python", "pai-thần"), ("Java", "gia-va"), ("Kotlin", "cót-lin"),
        ("Swift", "sờ-uýp"), ("Dart", "đát"), ("Flutter", "flớ-tờ"),
        ("PHP", "pi ét-ch"), ("Ruby", "ru-bi"), ("Golang", "gô-lang"),
        ("Go", "gô"), ("Rust", "rớt"), ("Scala", "sờ-ca-la"),
        ("Haskell", "hát-sờ-cồ"), ("Perl", "pơl"), ("Lua", "lu-a"),
        ("Node.js", "nốt giây ét"), ("NodeJS", "nốt giây ét"), ("Node", "nốt"),
        ("Deno", "đi-nô"), ("Bun", "bân"), ("runtime", "rân-taim"),
        ("runtime environment", "rân-taim en-vai-rần-mần"), ("JVM", "giây vi-em"),
        ("JRE", "giây a"), ("JDK", "giây đi cây"), ("SDK", "ét đi cây"),
        ("CLI", "xi eo ai"), ("REPL", "rếp-ồ"),
    ),
    "backend_api": (
        ("Representational State Transfer API", "re-pri-zen-tây-sần-nồ stây-tờ tran-sờ-phờ ây-pi-ai"),
        ("REST API", "rest ây-pi-ai"), ("RESTful API", "rest-phồ ây-pi-ai"),
        ("GraphQL", "gráp kiu eo"), ("gRPC", "gi a pi xi"),
        ("WebSocket", "web-sóc-kịt"), ("WebSockets", "web-sóc-kịt"),
        ("Server-Sent Events", "sơ-vờ sent i-ven"), ("SSE", "ét ét i"),
        ("Remote Procedure Call", "ri-mốt prờ-xi-giờ còl"), ("RPC", "a pi xi"),
        ("application programming interface", "áp-li-kây-sần prô-grêm-ming in-tờ-phây-sờ"),
        ("API gateway", "ây-pi-ai gât-uây"), ("API Gateway", "ây-pi-ai gât-uây"),
        ("API endpoint", "ây-pi-ai en-poin"), ("endpoint", "en-poin"),
        ("middleware", "mid-ồ-ue"), ("microservice", "mai-crô-sơ-vịt"),
        ("microservices", "mai-crô-sơ-vịt"), ("monolith", "mo-nờ-lít"),
        ("serverless", "sơ-vờ-lét"), ("event-driven", "i-vent dri-vần"),
        ("message queue", "me-sịt kiu"), ("message broker", "me-sịt brô-cờ"),
        ("idempotency", "ai-đem-pô-tần-si"), ("CRUD", "cru-đ"),
        ("Create Read Update Delete", "cờ-ri-ây-t ri-đ ấp-đây-t đì-lít"),
        ("MVC", "em vi xi"), ("MVVM", "em vi vi-em"), ("MVP", "em vi pi"),
        ("OOP", "âu âu pi"), ("object-oriented programming", "óp-giẹc ô-ri-en-tịt prô-grêm-ming"),
        ("SOLID", "sô-lịt"), ("DRY", "đờ-rai"), ("KISS", "kít"), ("YAGNI", "iếc-ni"),
        ("dependency injection", "đi-pen-đần-si in-giéc-sần"),
        ("dependency inversion", "đi-pen-đần-si in-vơ-sần"),
        ("inversion of control", "in-vơ-sần ợp cờn-trô"), ("IoC", "ai âu xi"),
        ("design pattern", "đi-zain pát-tần"), ("repository pattern", "ri-pó-zi-tơ-ri pát-tần"),
        ("rate limit", "rât li-mịt"), ("rate limiting", "rât li-mi-ting"),
        ("pagination", "pa-gi-nây-sần"), ("retry", "ri-trai"), ("timeout", "taim-out"),
        ("load balancing", "lô-đ ba-lần-sing"), ("load balancer", "lô-đ ba-lần-sờ"),
    ),
    "protocols_formats": (
        ("HyperText Markup Language", "hai-pờ-tek mark-ấp lang-uỵt"), ("HTML", "ây-chờ-ti-em-en"),
        ("Cascading Style Sheets", "cát-kây-đing stai-ồ shít"), ("CSS", "xi-ét-ét"),
        ("SCSS", "ét-xi-ét-ét"), ("Sass", "sát"), ("LESS", "let"),
        ("JSON Web Token", "giây-sần web tô-kần"), ("JWT", "giây đắp-bồ-liu-ti"),
        ("JSON", "giây-sần"), ("XML", "ích-em-en"), ("YAML", "ya-mồ"),
        ("CSV", "xi ét vi"), ("Markdown", "mark-đao"), ("HTTP", "ây-chờ-ti-ti-pi"),
        ("HTTPS", "ây-chờ-ti-ti-pi-ét"), ("HTTP/2", "ây-chờ-ti-ti-pi hai"),
        ("HTTP/3", "ây-chờ-ti-ti-pi ba"), ("TCP/IP", "ti-xi-pi ai-pi"),
        ("TCP", "ti-xi-pi"), ("UDP", "iu-đi-pi"), ("DNS", "đi-en-ét"),
        ("URL", "iu-a eo"), ("URI", "iu-a ai"), ("URN", "iu-a en"),
        ("CDN", "xi-đi-en"), ("SSL/TLS", "ét ét eo ti eo ét"), ("SSL", "ét ét eo"),
        ("TLS", "ti eo ét"), ("SSH", "ét ét ch"), ("FTP", "ép ti pi"),
        ("SFTP", "ét ép ti pi"), ("SMTP", "ét-em-ti-pi"), ("OAuth", "ô-auth"),
        ("OpenID Connect", "ô-pần ai-đi cờ-néc"), ("OIDC", "ô ai đi xi"),
        ("CORS", "coz"), ("CSRF", "xi ét a ép"), ("XSS", "ích ét ét"),
        ("MIME type", "mai-mờ taip"), ("webhook", "web-húc"), ("deep link", "đíp link"),
        ("link", "linh"), ("cookie", "cu-ki"), ("session", "se-sần"),
        ("token", "tô-kần"), ("payload", "pây-lô-đ"), ("header", "he-đờ"),
        ("query string", "que-ri string"), ("query parameter", "que-ri pa-ra-mi-tờ"),
    ),
    "databases_data": (
        ("PostgreSQL", "pốt-gờ-rét kiu-êu"), ("Postgres", "pốt-gờ-rét"),
        ("MySQL", "mai ét kiu eo"), ("Microsoft SQL Server", "mai-cờ-rô-soft ét kiu eo sơ-vờ"),
        ("SQL Server", "ét kiu eo sơ-vờ"), ("SQLite", "ét kiu lai-t"),
        ("MongoDB", "mong-gô đi-bi"), ("Mongo", "mong-gô"), ("Redis", "re-đít"),
        ("MariaDB", "ma-ri-a đi-bi"), ("Oracle", "o-rờ-cồ"), ("DynamoDB", "đai-na-mô đi-bi"),
        ("Cassandra", "ca-san-đờ-ra"), ("CouchDB", "cau-ch đi-bi"),
        ("Elasticsearch", "i-lát-tịc-sớt"), ("Firestore", "phaiờ-sto"),
        ("Supabase", "su-pờ-bâys"), ("PostGIS", "pốt-gi-ét"), ("NoSQL", "nô ét kiu eo"),
        ("SQL", "ét kiu eo"), ("database", "đây-tờ-bâys"),
        ("database schema", "đây-tờ-bâys ski-ma"), ("schema", "ski-ma"),
        ("relational database", "ri-lây-sần-nồ đây-tờ-bâys"), ("ORM", "âu a-em"),
        ("ODM", "âu đi-em"), ("Prisma", "prít-ma"), ("Mongoose", "mong-gút"),
        ("Sequelize", "si-qui-lai-z"), ("SQLAlchemy", "ét kiu eo an-kờ-mi"),
        ("Hibernate", "hai-bờ-nây-t"), ("migration", "mai-grây-sần"),
        ("migration script", "mai-grây-sần sờ-cờ-ríp"), ("query", "que-ri"),
        ("index", "in-đéc"), ("cache", "kesh"), ("caching", "ke-shing"),
        ("ACID", "a-sịt"), ("CAP theorem", "cáp thi-ờ-rầm"),
        ("eventual consistency", "i-ven-chu-ồ cờn-sít-tần-si"), ("data lake", "đây-tờ lâyk"),
        ("data warehouse", "đây-tờ ue-hao"), ("ETL", "i-ti-el"), ("ELT", "i-el-ti"),
        ("data pipeline", "đây-tờ pai-lain"), ("Kafka", "ca-phờ-ka"),
        ("RabbitMQ", "ra-bit-em-kiu"),
    ),
    "cloud_devops": (
        ("Amazon Web Services", "a-ma-zon web sơ-vịt"), ("AWS", "ây đắp-bồ-liu ét"),
        ("Microsoft Azure", "mai-cờ-rô-soft a-giu"), ("Azure", "a-giu"),
        ("Google Cloud Platform", "gu-gồ clao plat-pho"), ("GCP", "gi xi pi"),
        ("Google Cloud", "gu-gồ clao"), ("EC2", "i xi hai"), ("S3", "ét thờ-ri"),
        ("Lambda", "lam-đờ"), ("CloudFront", "clao-đ phờ-rân"), ("Route 53", "rút năm-ba"),
        ("IAM", "ai ây-em"), ("VPC", "vi pi xi"), ("RDS", "a đi ét"),
        ("Docker Compose", "đóc-cờ cờm-pô-z"), ("Docker", "đóc-cờ"),
        ("Kubernetes", "ku-bờ-nét-tịt"), ("K8s", "kây-t ét"), ("Helm", "hem"),
        ("container", "cờn-tây-nờ"), ("containerization", "cờn-tây-nờ-rờ-zây-sần"),
        ("image registry", "i-mịt re-gi-sờ-tri"), ("Terraform", "tê-rờ-pho"),
        ("Ansible", "an-si-bồ"), ("Pulumi", "pu-lu-mi"), ("Nginx", "en-jin-ích"),
        ("Apache", "a-pát-chi"), ("Linux", "li-núc"), ("Ubuntu", "u-bun-tu"),
        ("Unix", "iu-ních"), ("DevOps", "đi-vóp"), ("DevSecOps", "đi-vóp sec ôp"),
        ("SRE", "ét a"), ("CI/CD", "xi-ai xi-đi"), ("CI CD", "xi-ai xi-đi"),
        ("continuous integration", "cờn-ti-niu-ợt in-tờ-grây-sần"),
        ("continuous delivery", "cờn-ti-niu-ợt đi-li-vờ-ri"),
        ("continuous deployment", "cờn-ti-niu-ợt đi-ploi-mần"),
        ("GitHub Actions", "ghít-hắp ắc-sần"), ("GitLab CI", "ghít-láp xi-ai"),
        ("GitLab", "ghít-láp"), ("GitHub", "ghít-hắp"), ("Bitbucket", "bít-bắc-kịt"),
        ("Jenkins", "jen-kin"), ("pipeline", "pai-lain"), ("build", "bịu-đ"),
        ("deploy", "đi-ploi"), ("deployment", "đi-ploi-mần"), ("rollback", "rôl-béc"),
        ("blue-green deployment", "blu grin đi-ploi-mần"),
        ("canary deployment", "cờ-ne-ri đi-ploi-mần"), ("observability", "óp-zờ-vờ-bi-li-ti"),
        ("monitoring", "mo-ni-tờ-ring"), ("logging", "lo-ging"), ("metrics", "me-trích"),
        ("tracing", "trây-sing"),
    ),
    "source_control": (
        ("version control system", "vơ-sần cờn-trô sí-stầm"), ("Git", "ghít"),
        ("Git repository", "ghít ri-pó-zi-tơ-ri"), ("pull request", "pul ri-quest"),
        ("pull requests", "pul ri-quest"), ("merge request", "mơ-gi ri-quest"),
        ("merge", "mơ-gi"), ("commit", "cờ-mít"), ("branch", "branh"),
        ("checkout", "chéch-out"), ("rebase", "ri-bâys"), ("cherry-pick", "che-ri-pích"),
        ("stash", "stesh"), ("diff", "đíp"), ("README", "ri-đi-mi"),
        ("issue", "i-shu"), ("ticket", "tí-kịt"), ("release", "ri-lít"),
        ("semantic versioning", "si-man-tịc vơ-sần-ning"), ("SemVer", "sem-vơ"),
        ("monorepo", "mo-nô-ri-pô"), ("package manager", "pá-kịt ma-ni-jờ"),
        ("npm", "en-pi-em"), ("pnpm", "pi-en-pi-em"), ("Yarn", "yon"),
    ),
    "testing_quality": (
        ("test-driven development", "test dri-vần đi-ve-lợp-mần"), ("TDD", "ti-đi-đi"),
        ("behavior-driven development", "bi-hây-vi-ờ dri-vần đi-ve-lợp-mần"), ("BDD", "bi-đi-đi"),
        ("unit test", "iu-nịt test"), ("unit testing", "iu-nịt te-sting"),
        ("integration test", "in-tờ-grây-sần test"), ("end-to-end test", "en tu en test"),
        ("E2E", "i tu i"), ("regression test", "ri-gre-sần test"), ("smoke test", "smôk test"),
        ("load test", "lô-đ test"), ("stress test", "stres test"), ("Jest", "jest"),
        ("Vitest", "vi-test"), ("Mocha", "mô-ca"), ("Cypress", "sai-prờs"),
        ("Playwright", "plây-rait"), ("Selenium", "si-li-ni-ầm"), ("Postman", "pốt-man"),
        ("mock", "móc"), ("stub", "stấp"), ("fixture", "phích-chờ"),
        ("test coverage", "test cờ-vờ-rịt"), ("code coverage", "cô-đ cờ-vờ-rịt"),
        ("quality assurance", "qua-li-ti a-shu-rần"), ("QA", "kiu ây"),
        ("acceptance criteria", "ắc-xép-tần cri-ti-ri-a"), ("test case", "test câys"),
        ("test suite", "test suýt"), ("bug", "bấc"), ("debug", "đi-bấc"),
        ("debugging", "đi-bấc-ging"), ("refactor", "ri-phác-tờ"), ("linter", "lin-tờ"),
        ("static analysis", "stát-tịc a-na-lí-sịt"),
    ),
    "security_identity": (
        ("cybersecurity", "sai-bờ si-kiu-ri-ti"), ("information security", "in-phờ-mây-sần si-kiu-ri-ti"),
        ("authentication", "o-then-ti-kây-sần"), ("authorization", "o-thờ-rai-zây-sần"),
        ("identity and access management", "ai-đen-ti-ti en-đ ắc-xét ma-ni-jờ-mần"),
        ("RBAC", "a-bi-âys"), ("ABAC", "ây-bi-âys"), ("single sign-on", "sing-gồ sain-on"),
        ("SSO", "ét ét ô"), ("multi-factor authentication", "mân-ti phác-tờ o-then-ti-kây-sần"),
        ("MFA", "em ép ây"), ("two-factor authentication", "tu phác-tờ o-then-ti-kây-sần"),
        ("2FA", "tu phác-tờ ây"), ("encryption", "en-crip-sần"), ("decryption", "đi-crip-sần"),
        ("hashing", "he-shing"), ("hash", "hesh"), ("salt", "sôn"), ("secret", "si-crit"),
        ("credential", "cờ-ren-sồ"), ("PII", "pi-ai-ai"), ("GDPR", "gi-đi-pi-a"),
        ("SOC 2", "sóc tu"), ("OWASP", "ô-uát"), ("SQL injection", "ét kiu eo in-giéc-sần"),
        ("cross-site scripting", "crót sait sờ-cờ-ríp-ting"), ("zero trust", "zi-rô trớt"),
        ("principle of least privilege", "prin-si-pồ ợp list pri-vờ-lịt"),
    ),
    "ai_voice": (
        ("Artificial Intelligence", "a-ti-fi-sồ in-te-li-jần-s"), ("Machine Learning", "mờ-shin lơ-ning"),
        ("Deep Learning", "đíp lơ-ning"), ("Natural Language Processing", "na-chờ-rồ lang-uỵt pro-se-sing"),
        ("AI", "ây-ai"), ("ML", "em-el"), ("DL", "đi-el"), ("NLP", "en-el-pi"),
        ("Large Language Model", "lát lang-uỵt mo-đồ"), ("LLM", "el-el-em"),
        ("Generative AI", "je-nờ-rờ-tịp ây-ai"), ("GenAI", "jen ây-ai"),
        ("Retrieval-Augmented Generation", "ri-tri-vồ o-men-tịt je-nờ-rây-sần"),
        ("RAG", "rag"), ("embedding", "em-be-đing"), ("vector database", "vec-tờ đây-tờ-bâys"),
        ("vector search", "vec-tờ sơ-ch"), ("transformer", "tran-pho-mờ"),
        ("fine-tuning", "phain-tiu-ning"), ("fine tuning", "phain-tiu-ning"),
        ("prompt engineering", "promt en-gi-ni-ờ-ring"), ("prompt", "promt"),
        ("tokenization", "tô-cờ-nai-zây-sần"), ("hallucination", "ha-lu-si-nây-sần"),
        ("DeepSeek", "đíp-sích"), ("OpenAI", "ô-pần ây-ai"), ("GPT", "gi-pi-ti"),
        ("ChatGPT", "chat gi-pi-ti"), ("Claude", "clo-đ"), ("Gemini", "je-mi-nai"),
        ("Whisper", "uýt-sờ"), ("SenseVoice", "sen-vois"), ("AssemblyAI", "a-sem-bli ây-ai"),
        ("speech-to-text", "spich tu text"), ("text-to-speech", "text tu spich"),
        ("TTS", "ti-ti-ét"), ("STT", "ét-ti-ti"), ("ASR", "ây ét a"),
        ("voice activity detection", "vois ắc-ti-vi-ti đi-tek-sần"), ("VAD", "vi ây đi"),
        ("real-time transcription", "ri-ồ taim tran-scrip-sần"), ("transcription", "tran-scrip-sần"),
        ("speech recognition", "spich re-cờ-ních-sần"), ("cosine similarity", "cô-zain si-mi-la-ri-ti"),
        ("temperature", "tem-pờ-rờ-chờ"), ("context window", "con-tex windô"),
        ("function calling", "phâng-sần co-ling"), ("structured output", "sờ-trắc-chờt out-put"),
        ("JSON mode", "giây-sần mô-đ"),
    ),
    "product_business": (
        ("Minimum Viable Product", "mi-ni-mầm vai-ờ-bồ pro-đấc"), ("MVP", "em vi pi"),
        ("proof of concept", "pru-ợp cờn-sept"), ("PoC", "pi ô xi"),
        ("key performance indicator", "ki pờ-pho-mần in-đi-kây-tờ"), ("KPI", "kay pi ai"),
        ("OKR", "ô kây a"), ("return on investment", "ri-tơn on in-vest-mần"), ("ROI", "a ô ai"),
        ("business-to-business", "bi-zờ-nịt tu bi-zờ-nịt"), ("B2B", "bi tu bi"),
        ("business-to-consumer", "bi-zờ-nịt tu cờn-siu-mờ"), ("B2C", "bi tu xi"),
        ("user story", "du-zờ sto-ri"), ("use case", "dụt câys"), ("roadmap", "rô-đ-map"),
        ("backlog", "béc-log"), ("sprint", "sờ-print"), ("scrum", "sờ-crầm"),
        ("Agile", "a-jai"), ("waterfall", "wo-tờ-phol"), ("stakeholder", "stâyk-hô-đờ"),
        ("product owner", "pro-đấc ô-nờ"), ("product manager", "pro-đấc ma-ni-jờ"),
        ("tech lead", "tek li-đ"), ("technical debt", "tek-ni-cồ đét"),
        ("user acceptance testing", "du-zờ ắc-xép-tần te-sting"), ("UAT", "iu ây ti"),
        ("customer journey", "cờs-tờ-mờ jo-ni"), ("A/B testing", "ây bi te-sting"),
        ("conversion rate", "cờn-vơ-sần rât"), ("churn rate", "chơn rât"),
        ("North Star Metric", "nọt star me-trích"), ("NPS", "en pi ét"),
    ),
    "industry_information_technology": (
        ("Software Engineer", "sóp-ue eng-gi-ni-ờ"), ("Software Developer", "sóp-ue đi-ve-lóp-pờ"),
        ("Frontend Developer", "phờ-rân-en đi-ve-lóp-pờ"), ("Front-End Developer", "phờ-rân-en đi-ve-lóp-pờ"),
        ("Backend Developer", "béc-en đi-ve-lóp-pờ"), ("Back-End Developer", "béc-en đi-ve-lóp-pờ"),
        ("Full Stack Developer", "ful stác đi-ve-lóp-pờ"), ("Full-Stack Developer", "ful stác đi-ve-lóp-pờ"),
        ("Mobile Developer", "mô-bai đi-ve-lóp-pờ"), ("Web Developer", "web đi-ve-lóp-pờ"),
        ("Application Developer", "áp-li-kây-sần đi-ve-lóp-pờ"), ("Game Developer", "gâym đi-ve-lóp-pờ"),
        ("DevOps Engineer", "đi-vóp eng-gi-ni-ờ"), ("DevSecOps Engineer", "đi-vóp sec ôp eng-gi-ni-ờ"),
        ("Site Reliability Engineer", "sait ri-lai-ờ-bi-li-ti eng-gi-ni-ờ"), ("SRE Engineer", "ét-a eng-gi-ni-ờ"),
        ("Cloud Engineer", "clao eng-gi-ni-ờ"), ("Platform Engineer", "plat-pho eng-gi-ni-ờ"),
        ("Infrastructure Engineer", "in-phờ-rờ-sờ-trắc-chờ eng-gi-ni-ờ"),
        ("Solutions Architect", "sờ-lu-sần-s a-ki-tek"), ("Software Architect", "sóp-ue a-ki-tek"),
        ("System Architect", "sít-stầm a-ki-tek"), ("Enterprise Architect", "en-tờ-prai-z a-ki-tek"),
        ("Technical Lead", "tek-ni-cồ li-đ"), ("Tech Lead", "tek li-đ"),
        ("Engineering Manager", "eng-gi-ni-ờ-ring ma-ni-jờ"), ("Engineering Director", "eng-gi-ni-ờ-ring đi-rec-tờ"),
        ("Chief Technology Officer", "chíp tek-nó-lờ-gi óp-fi-sờ"), ("CTO", "xi-ti-ô"),
        ("Quality Assurance Engineer", "qua-li-ti a-shu-rần eng-gi-ni-ờ"), ("QA Engineer", "kiu ây eng-gi-ni-ờ"),
        ("Automation Tester", "o-tờ-mây-sần test-tờ"), ("Manual Tester", "man-iu-ồ test-tờ"),
        ("Security Engineer", "si-kiu-ri-ti eng-gi-ni-ờ"), ("Security Analyst", "si-kiu-ri-ti a-na-list"),
        ("Penetration Tester", "pe-ni-trây-sần test-tờ"), ("Pen Tester", "pen test-tờ"),
        ("Network Engineer", "net-uốc eng-gi-ni-ờ"), ("System Administrator", "sít-stầm át-min-ni-strây-tờ"),
        ("Database Administrator", "đây-tờ-bâys át-min-ni-strây-tờ"), ("DBA", "đi-bi-ây"),
        ("Business Analyst", "bi-zờ-nịt a-na-list"), ("Systems Analyst", "sít-stầm a-na-list"),
        ("Data Analyst", "đây-tờ a-na-list"), ("Technical Writer", "tek-ni-cồ rai-tờ"),
        ("Support Engineer", "sờ-pót eng-gi-ni-ờ"), ("IT Support", "ai-ti sờ-pót"),
        ("IT Manager", "ai-ti ma-ni-jờ"), ("Chief Information Officer", "chíp in-phờ-mây-sần óp-fi-sờ"),
        ("CIO", "xi-ai-ô"), ("information technology", "in-phờ-mây-sần tek-nó-lờ-gi"),
        ("software development life cycle", "sóp-ue đi-ve-lóp-mần lai-ph sai-cồ"), ("SDLC", "ét-đi-el-xi"),
        ("object-oriented", "óp-giẹc ô-ri-en-tịt"), ("functional programming", "phâng-sần-nồ prô-grêm-ming"),
        ("clean code", "clin cô-đ"), ("technical interview", "tek-ni-cồ in-tờ-viu"),
    ),
    "industry_data_ai": (
        ("Data Scientist", "đây-tờ sai-ần-tịt"), ("Data Engineer", "đây-tờ eng-gi-ni-ờ"),
        ("Machine Learning Engineer", "mờ-shin lơ-ning eng-gi-ni-ờ"),
        ("Machine Learning Scientist", "mờ-shin lơ-ning sai-ần-tịt"),
        ("AI Engineer", "ây-ai eng-gi-ni-ờ"), ("AI Researcher", "ây-ai ri-sơ-chờ"),
        ("Research Scientist", "ri-sơ-ch sai-ần-tịt"), ("Research Engineer", "ri-sơ-ch eng-gi-ni-ờ"),
        ("MLOps Engineer", "em-el-óp-s eng-gi-ni-ờ"), ("ML Engineer", "em-el eng-gi-ni-ờ"),
        ("NLP Engineer", "en-el-pi eng-gi-ni-ờ"), ("Computer Vision Engineer", "cờm-piu-tờ vi-giần eng-gi-ni-ờ"),
        ("Data Architect", "đây-tờ a-ki-tek"), ("Data Warehouse Engineer", "đây-tờ ue-hao eng-gi-ni-ờ"),
        ("Analytics Engineer", "a-na-lí-tịc eng-gi-ni-ờ"), ("BI Developer", "bi-ai đi-ve-lóp-pờ"),
        ("Business Intelligence Analyst", "bi-zờ-nịt in-te-li-jần-s a-na-list"),
        ("BI Analyst", "bi-ai a-na-list"), ("Quantitative Analyst", "quan-ti-tây-tịp a-na-list"),
        ("Quant Analyst", "quant a-na-list"), ("Statistician", "stờ-ti-sti-sần"),
        ("Data Product Manager", "đây-tờ pro-đấc ma-ni-jờ"), ("Prompt Engineer", "promt eng-gi-ni-ờ"),
        ("AI Product Manager", "ây-ai pro-đấc ma-ni-jờ"), ("Data Governance", "đây-tờ gơ-vờ-nần-s"),
        ("data governance", "đây-tờ gơ-vờ-nần-s"), ("data quality", "đây-tờ qua-li-ti"),
        ("data privacy", "đây-tờ prai-vờ-si"), ("data visualization", "đây-tờ vi-giu-ồ-lai-zây-sần"),
        ("dashboard", "đesh-bọt"), ("feature engineering", "phi-chờ eng-gi-ni-ờ-ring"),
        ("model training", "mo-đồ trây-ning"), ("model serving", "mo-đồ sơ-ving"),
        ("model monitoring", "mo-đồ mo-ni-tờ-ring"), ("AIOps", "ây-ai-óp-s"),
        ("computer science", "cờm-piu-tờ sai-ần-s"), ("data science", "đây-tờ sai-ần-s"),
        ("big data", "big đây-tờ"), ("time series", "taim si-ri"),
        ("natural language", "na-chờ-rồ lang-uỵt"), ("recommendation system", "re-cờ-men-đây-sần sí-stầm"),
        ("classification", "cla-si-fi-kây-sần"), ("regression", "ri-gre-sần"),
        ("clustering", "clớt-tờ-ring"), ("A/B experiment", "ây bi ích-xpe-ri-mần"),
    ),
    "industry_finance_banking": (
        ("Financial Analyst", "phai-nan-sồ a-na-list"), ("Investment Analyst", "in-vest-mần a-na-list"),
        ("Investment Banker", "in-vest-mần beng-kờ"), ("Equity Analyst", "e-qui-ti a-na-list"),
        ("Credit Analyst", "cre-địt a-na-list"), ("Risk Analyst", "rítk a-na-list"),
        ("Risk Manager", "rítk ma-ni-jờ"), ("Portfolio Manager", "pót-phô-li-ô ma-ni-jờ"),
        ("Fund Manager", "phâng ma-ni-jờ"), ("Asset Manager", "a-set ma-ni-jờ"),
        ("Wealth Manager", "uel-th ma-ni-jờ"), ("Relationship Manager", "ri-lây-sần-ship ma-ni-jờ"),
        ("Treasury Analyst", "tre-giờ-ri a-na-list"), ("Treasury Manager", "tre-giờ-ri ma-ni-jờ"),
        ("Financial Controller", "phai-nan-sồ cờn-trô-lờ"), ("CFO", "xi-ép-ô"),
        ("Chief Financial Officer", "chíp phai-nan-sồ óp-fi-sờ"), ("Chief Risk Officer", "chíp rítk óp-fi-sờ"),
        ("CRO", "xi-a-ô"), ("Bank Teller", "beng-k te-lờ"), ("Loan Officer", "lôn óp-fi-sờ"),
        ("Credit Officer", "cre-địt óp-fi-sờ"), ("Underwriter", "ân-đờ-rai-tờ"),
        ("Actuary", "ắc-chu-ờ-ri"), ("Quantitative Researcher", "quan-ti-tây-tịp ri-sơ-chờ"),
        ("Compliance Officer", "cờm-plai-ần-s óp-fi-sờ"), ("AML Analyst", "ây-em-el a-na-list"),
        ("Anti-Money Laundering", "an-ti mân-ni lon-đờ-ring"), ("KYC Analyst", "kay-uai-xi a-na-list"),
        ("Know Your Customer", "nô yo cờs-tờ-mờ"), ("FinTech", "phin-tek"),
        ("financial technology", "phai-nan-sồ tek-nó-lờ-gi"), ("retail banking", "ri-tâyl beng-king"),
        ("corporate banking", "co-pờ-rịt beng-king"), ("commercial banking", "cờ-mơ-sồ beng-king"),
        ("investment banking", "in-vest-mần beng-king"), ("capital market", "ca-pi-tồ ma-kịt"),
        ("financial market", "phai-nan-sồ ma-kịt"), ("cash flow", "kesh flô"),
        ("balance sheet", "ba-lần shít"), ("income statement", "in-cầm stây-mần"),
        ("profit and loss", "pro-fit en-đ los"), ("P&L", "pi en-đ el"),
        ("gross margin", "grôs ma-jin"), ("net margin", "net ma-jin"),
        ("EBITDA", "i-bi-đi-a"), ("IRR", "ai-a-a"), ("NPV", "en pi vi"),
        ("ROE", "a ô i"), ("ROA", "a ô ây"), ("credit score", "cre-địt sco"),
        ("interest rate", "in-tờ-rest rât"), ("exchange rate", "ích-châynj rât"),
        ("liquidity", "li-qui-đi-ti"), ("solvency", "sol-vần-si"), ("hedging", "he-ging"),
    ),
    "industry_sales_business": (
        ("Sales Representative", "sâylz re-pri-zen-tờ-tịp"), ("Sales Executive", "sâylz ích-xe-kiu-tịp"),
        ("Sales Manager", "sâylz ma-ni-jờ"), ("Sales Director", "sâylz đi-rec-tờ"),
        ("Business Development Representative", "bi-zờ-nịt đi-ve-lóp-mần re-pri-zen-tờ-tịp"),
        ("Business Development Manager", "bi-zờ-nịt đi-ve-lóp-mần ma-ni-jờ"),
        ("BDR", "bi-đi-a"), ("Account Executive", "ờ-cao-nt ích-xe-kiu-tịp"),
        ("Account Manager", "ờ-cao-nt ma-ni-jờ"), ("Key Account Manager", "ki ờ-cao-nt ma-ni-jờ"),
        ("Key Account", "ki ờ-cao-nt"), ("Sales Engineer", "sâylz eng-gi-ni-ờ"),
        ("Pre-Sales Consultant", "pri-sâylz cờn-sân-tần"), ("Sales Operations", "sâylz óp-pờ-rây-sần"),
        ("Revenue Operations", "re-vờ-niu óp-pờ-rây-sần"), ("RevOps", "rev óp-s"),
        ("Customer Success Manager", "cờs-tờ-mờ sờc-sét ma-ni-jờ"), ("Customer Success", "cờs-tờ-mờ sờc-sét"),
        ("Partnership Manager", "pát-nờ-ship ma-ni-jờ"), ("Channel Manager", "cha-nồ ma-ni-jờ"),
        ("Territory Manager", "te-ri-to-ri ma-ni-jờ"), ("Merchandiser", "mơ-chần-đai-zờ"),
        ("Business Development", "bi-zờ-nịt đi-ve-lóp-mần"), ("sales pipeline", "sâylz pai-lain"),
        ("sales funnel", "sâylz phâng-nồ"), ("lead generation", "li-đ je-nờ-rây-sần"),
        ("lead qualification", "li-đ qua-li-fi-kây-sần"), ("prospect", "pro-spect"),
        ("outbound sales", "out-bao-nd sâylz"), ("inbound sales", "in-bao-nd sâylz"),
        ("enterprise sales", "en-tờ-prai-z sâylz"), ("solution selling", "sờ-lu-sần se-ling"),
        ("consultative selling", "cờn-sân-tờ-tịp se-ling"), ("upselling", "ấp-se-ling"),
        ("cross-selling", "crót-se-ling"), ("quota", "quo-tờ"), ("commission", "cờ-mi-sần"),
        ("pipeline coverage", "pai-lain cờ-vờ-rịt"), ("win rate", "win rât"),
        ("close rate", "clôz rât"), ("average deal size", "a-vờ-rịt đil saiz"),
        ("customer lifetime value", "cờs-tờ-mờ lai-ph taim va-liu"), ("CLV", "xi-el-vi"),
        ("customer acquisition cost", "cờs-tờ-mờ a-qui-zi-sần cost"), ("CAC", "các"),
        ("annual recurring revenue", "an-niu-ồ ri-cơ-ring re-vờ-niu"), ("ARR", "ây-a-a"),
        ("monthly recurring revenue", "mân-thờ-li ri-cơ-ring re-vờ-niu"), ("MRR", "em-a-a"),
    ),
    "industry_marketing_advertising": (
        ("Marketing Executive", "ma-kịt-ting ích-xe-kiu-tịp"), ("Marketing Manager", "ma-kịt-ting ma-ni-jờ"),
        ("Marketing Director", "ma-kịt-ting đi-rec-tờ"), ("Digital Marketing Specialist", "đi-gi-tồ ma-kịt-ting spe-sờ-list"),
        ("Content Marketing Specialist", "con-tent ma-kịt-ting spe-sờ-list"),
        ("Content Writer", "con-tent rai-tờ"), ("Copywriter", "co-pi rai-tờ"),
        ("Content Creator", "con-tent cri-ây-tờ"), ("Social Media Specialist", "sô-sồ mi-đi-a spe-sờ-list"),
        ("Social Media Manager", "sô-sồ mi-đi-a ma-ni-jờ"), ("SEO Specialist", "ét-i-ô spe-sờ-list"),
        ("SEM Specialist", "ét-i-em spe-sờ-list"), ("Performance Marketing", "pờ-pho-mần ma-kịt-ting"),
        ("Growth Marketing", "grâu-th ma-kịt-ting"), ("Growth Hacker", "grâu-th he-kờ"),
        ("Brand Manager", "brand ma-ni-jờ"), ("Brand Strategist", "brand sờ-tra-tờ-jist"),
        ("Product Marketing Manager", "pro-đấc ma-kịt-ting ma-ni-jờ"),
        ("Trade Marketing Manager", "trâyd ma-kịt-ting ma-ni-jờ"), ("PR Specialist", "pi-a spe-sờ-list"),
        ("Public Relations", "pắp-lic ri-lây-sần-s"), ("Communications Manager", "cờ-miu-ni-kây-sần-s ma-ni-jờ"),
        ("Influencer Marketing", "in-flu-en-sờ ma-kịt-ting"), ("Affiliate Marketing", "ờ-fi-li-ây-t ma-kịt-ting"),
        ("Email Marketing", "i-mâyl ma-kịt-ting"), ("CRM Manager", "xi-a-em ma-ni-jờ"),
        ("Market Researcher", "ma-kịt ri-sơ-chờ"), ("Consumer Insights Analyst", "cờn-siu-mờ in-sait-s a-na-list"),
        ("Media Planner", "mi-đi-a pla-nờ"), ("Media Buyer", "mi-đi-a bai-ờ"),
        ("Creative Director", "cri-ây-tịp đi-rec-tờ"), ("Art Director", "ạt đi-rec-tờ"),
        ("Account Planner", "ờ-cao-nt pla-nờ"), ("Account Director", "ờ-cao-nt đi-rec-tờ"),
        ("Campaign Manager", "cam-pâyn ma-ni-jờ"), ("Marketing Analyst", "ma-kịt-ting a-na-list"),
        ("marketing strategy", "ma-kịt-ting sờ-tra-tờ-gi"), ("marketing funnel", "ma-kịt-ting phâng-nồ"),
        ("brand awareness", "brand ờ-ue-nịt"), ("brand equity", "brand e-qui-ti"),
        ("target audience", "ta-gịt o-đi-ần-s"), ("buyer persona", "bai-ờ pờ-sô-na"),
        ("customer journey", "cờs-tờ-mờ jo-ni"), ("conversion rate", "cờn-vơ-sần rât"),
        ("click-through rate", "clích-thru rât"), ("CTR", "xi-ti-a"),
        ("cost per click", "cost pờ clích"), ("CPC", "xi-pi-xi"),
        ("cost per acquisition", "cost pờ a-qui-zi-sần"), ("CPA", "xi-pi-ây"),
        ("return on ad spend", "ri-tơn on ad spend"), ("ROAS", "rô-át"),
        ("search engine optimization", "sơ-ch en-jin óp-ti-mai-zây-sần"),
        ("search engine marketing", "sơ-ch en-jin ma-kịt-ting"),
    ),
    "industry_human_resources": (
        ("Human Resources Specialist", "h iu-man ri-só-sịt spe-sờ-list"),
        ("Human Resources Manager", "h iu-man ri-só-sịt ma-ni-jờ"),
        ("HR Business Partner", "ây-ch a bi-zờ-nịt pát-nờ"), ("HRBP", "ây-ch a bi-pi"),
        ("HR Generalist", "ây-ch a je-nờ-rờ-list"), ("HR Specialist", "ây-ch a spe-sờ-list"),
        ("Talent Acquisition Specialist", "ta-lần ắc-qui-zi-sần spe-sờ-list"),
        ("Talent Acquisition Manager", "ta-lần ắc-qui-zi-sần ma-ni-jờ"),
        ("Recruiter", "ri-cru-tờ"), ("Technical Recruiter", "tek-ni-cồ ri-cru-tờ"),
        ("Executive Recruiter", "ích-xe-kiu-tịp ri-cru-tờ"), ("Sourcer", "sau-sờ"),
        ("People Operations", "pi-pồ óp-pờ-rây-sần"), ("People Partner", "pi-pồ pát-nờ"),
        ("Learning and Development", "lơ-ning en-đ đi-ve-lóp-mần"), ("L&D", "el en-đ đi"),
        ("Learning Specialist", "lơ-ning spe-sờ-list"), ("Compensation and Benefits", "com-pen-sây-sần en-đ be-ne-fit-s"),
        ("C&B", "xi en-đ bi"), ("Payroll Specialist", "pây-rôl spe-sờ-list"),
        ("Employer Branding", "em-ploi-ờ brand-đing"), ("Employee Relations", "em-ploi-i ri-lây-sần-s"),
        ("Organizational Development", "o-gờ-nai-zây-sần-nồ đi-ve-lóp-mần"),
        ("People Analytics", "pi-pồ a-na-lí-tịc"), ("Chief Human Resources Officer", "chíp h iu-man ri-só-sịt óp-fi-sờ"),
        ("CHRO", "xi-ch a-ô"), ("performance review", "pờ-pho-mần ri-viu"),
        ("succession planning", "sắc-se-sần pla-ning"), ("competency framework", "com-pờ-tần-si phờ-râym-quớc"),
        ("job description", "giop đi-scrip-sần"), ("employee engagement", "em-ploi-i en-gâyj-mần"),
        ("retention rate", "ri-ten-sần rât"), ("attrition rate", "ờ-tri-sần rât"),
        ("time to hire", "taim tu hai-ờ"), ("time to fill", "taim tu phil"),
        ("cost per hire", "cost pờ hai-ờ"), ("candidate experience", "can-đi-đâyt ích-xpi-ri-ần-sờ"),
        ("onboarding", "on-bo-đing"), ("offboarding", "of-bo-đing"), ("upskilling", "ấp-ski-ling"),
        ("reskilling", "ri-ski-ling"), ("workforce planning", "uốc-pho-s pla-ning"),
        ("people strategy", "pi-pồ sờ-tra-tờ-gi"), ("organizational culture", "o-gờ-nai-zây-sần-nồ cấl-chờ"),
    ),
    "industry_customer_service": (
        ("Customer Service Representative", "cờs-tờ-mờ sơ-vịt re-pri-zen-tờ-tịp"),
        ("Customer Service Agent", "cờs-tờ-mờ sơ-vịt ây-jần"), ("Customer Service Manager", "cờs-tờ-mờ sơ-vịt ma-ni-jờ"),
        ("Customer Support Specialist", "cờs-tờ-mờ sờ-pót spe-sờ-list"),
        ("Technical Support Specialist", "tek-ni-cồ sờ-pót spe-sờ-list"),
        ("Call Center Agent", "col sen-tờ ây-jần"), ("Contact Center Manager", "con-tact sen-tờ ma-ni-jờ"),
        ("Help Desk Technician", "help desk tek-ni-sần"), ("Service Desk Analyst", "sơ-vịt desk a-na-list"),
        ("Customer Experience Manager", "cờs-tờ-mờ ích-xpi-ri-ần-sờ ma-ni-jờ"), ("CX Manager", "xi ích ma-ni-jờ"),
        ("Customer Success Specialist", "cờs-tờ-mờ sờc-sét spe-sờ-list"),
        ("Client Services Manager", "clai-ần sơ-vịt ma-ni-jờ"), ("Community Manager", "cờ-miu-ni-ti ma-ni-jờ"),
        ("Escalation Manager", "es-cờ-lây-sần ma-ni-jờ"), ("Service Delivery Manager", "sơ-vịt đi-li-vờ-ri ma-ni-jờ"),
        ("customer support", "cờs-tờ-mờ sờ-pót"), ("customer service", "cờs-tờ-mờ sơ-vịt"),
        ("service level agreement", "sơ-vịt le-vồ ờ-gri-mần"), ("SLA", "ét-el-ây"),
        ("first response time", "phớt ri-spon-s taim"), ("FRT", "ép-a-ti"),
        ("average handling time", "a-vờ-rịt hen-đờ-ling taim"), ("AHT", "ây-ch-ti"),
        ("first contact resolution", "phớt con-tact re-zờ-lu-sần"), ("FCR", "ép-xi-a"),
        ("customer satisfaction", "cờs-tờ-mờ sat-tịt-phác-sần"), ("CSAT", "xi-sat"),
        ("net promoter score", "net prờ-mô-tờ sco"), ("customer effort score", "cờs-tờ-mờ e-phọt sco"),
        ("knowledge base", "nó-lịtj bâys"), ("ticketing system", "tí-kịt-ting sí-stầm"),
        ("live chat", "laiv chat"), ("voice of customer", "vois ợp cờs-tờ-mờ"), ("VOC", "vi-ô-xi"),
        ("complaint handling", "cờm-pleynt hen-đờ-ling"), ("root cause analysis", "rut coz a-na-lí-sịt"),
    ),
    "industry_design_creative": (
        ("Graphic Designer", "gráp-phíc đi-zai-nờ"), ("Visual Designer", "vi-giu-ồ đi-zai-nờ"),
        ("Product Designer", "pro-đấc đi-zai-nờ"), ("UX Designer", "diu-ích đi-zai-nờ"),
        ("UI Designer", "diu-ai đi-zai-nờ"), ("UX Researcher", "diu-ích ri-sơ-chờ"),
        ("User Researcher", "du-zờ ri-sơ-chờ"), ("Interaction Designer", "in-tờ-rắc-sần đi-zai-nờ"),
        ("Service Designer", "sơ-vịt đi-zai-nờ"), ("Design Lead", "đi-zain li-đ"),
        ("Design Manager", "đi-zain ma-ni-jờ"), ("Creative Director", "cri-ây-tịp đi-rec-tờ"),
        ("Art Director", "ạt đi-rec-tờ"), ("Art Designer", "ạt đi-zai-nờ"),
        ("Motion Designer", "mô-sần đi-zai-nờ"), ("Motion Graphics Designer", "mô-sần gráp-phíc đi-zai-nờ"),
        ("3D Artist", "thờ-ri đi a-tịt"), ("Illustrator", "i-lớt-trây-tờ"),
        ("Animator", "a-ni-mây-tờ"), ("Photographer", "phờ-tó-gờ-rờ-phờ"),
        ("Videographer", "vi-đi-ô-gờ-rờ-phờ"), ("Video Editor", "vi-đi-ô e-đi-tờ"),
        ("Copywriter", "co-pi rai-tờ"), ("Creative Strategist", "cri-ây-tịp sờ-tra-tờ-jist"),
        ("Brand Designer", "brand đi-zai-nờ"), ("Interior Designer", "in-ti-ri-ờ đi-zai-nờ"),
        ("Fashion Designer", "pha-sần đi-zai-nờ"), ("design brief", "đi-zain brip"),
        ("design critique", "đi-zain cờ-rít"), ("design review", "đi-zain ri-viu"),
        ("user flow", "du-zờ flô"), ("user journey", "du-zờ jo-ni"), ("user persona", "du-zờ pờ-sô-na"),
        ("usability testing", "iu-zi-bi-li-ti te-sting"), ("usability", "iu-zi-bi-li-ti"),
        ("information architecture", "in-phờ-mây-sần a-ki-tek-chờ"),
        ("visual hierarchy", "vi-giu-ồ hai-ờ-ki"), ("color theory", "cờ-lờ thi-ờ-ri"),
        ("typography", "tai-pó-gờ-rờ-phi"), ("layout", "lây-out"), ("grid system", "grid sí-stầm"),
        ("design token", "đi-zain tô-kần"), ("component library", "cờm-pô-nần lai-bờ-re-ri"),
        ("high-fidelity prototype", "hai fi-đe-li-ti prô-tờ-taip"), ("low-fidelity prototype", "lô fi-đe-li-ti prô-tờ-taip"),
        ("A/B testing", "ây bi te-sting"), ("design ops", "đi-zain óp-s"),
        ("accessibility", "ắc-xe-si-bi-li-ti"), ("WCAG", "đắp-bồ-liu-cag"),
    ),
    "industry_accounting_audit": (
        ("Accountant", "ờ-cao-nt-tần"), ("Senior Accountant", "si-ni-ờ ờ-cao-nt-tần"),
        ("Chief Accountant", "chíp ờ-cao-nt-tần"), ("Accounting Manager", "ờ-cao-nt-ting ma-ni-jờ"),
        ("Financial Accountant", "phai-nan-sồ ờ-cao-nt-tần"), ("Management Accountant", "ma-ni-j-mần ờ-cao-nt-tần"),
        ("Tax Accountant", "tax ờ-cao-nt-tần"), ("Tax Consultant", "tax cờn-sân-tần"),
        ("Auditor", "o-đi-tờ"), ("Internal Auditor", "in-tơ-nồ o-đi-tờ"),
        ("External Auditor", "ích-stơ-nồ o-đi-tờ"), ("Audit Manager", "o-địt ma-ni-jờ"),
        ("Audit Partner", "o-địt pát-nờ"), ("Forensic Accountant", "phờ-ren-sịt ờ-cao-nt-tần"),
        ("Bookkeeper", "búc-ki-pờ"), ("Accounts Payable", "ờ-cao-nt-s pây-ờ-bồ"),
        ("Accounts Receivable", "ờ-cao-nt-s ri-si-vờ-bồ"), ("AP Accountant", "ây-pi ờ-cao-nt-tần"),
        ("AR Accountant", "ây-a ờ-cao-nt-tần"), ("Controller", "cờn-trô-lờ"),
        ("CFO", "xi-ép-ô"), ("Generally Accepted Accounting Principles", "je-nờ-rờ-li ắc-sep-tịt ờ-cao-nt-ting prin-si-pồ-s"),
        ("GAAP", "gáp"), ("International Financial Reporting Standards", "in-tờ-na-sần-nồ phai-nan-sồ ri-pót-ting stân-đờt-s"),
        ("IFRS", "ai-ép-a"), ("financial statement", "phai-nan-sồ stây-mần"),
        ("general ledger", "je-nờ-rồ le-jờ"), ("trial balance", "trai-ồ ba-lần-s"),
        ("accounts payable", "ờ-cao-nt-s pây-ờ-bồ"), ("accounts receivable", "ờ-cao-nt-s ri-si-vờ-bồ"),
        ("reconciliation", "re-con-si-li-ây-sần"), ("cash flow statement", "kesh flô stây-mần"),
        ("budgeting", "bấ-gi-ting"), ("forecasting", "pho-cát-ting"), ("variance analysis", "ve-ri-ần-s a-na-lí-sịt"),
        ("internal control", "in-tơ-nồ cờn-trô"), ("material misstatement", "mờ-ti-ri-ồ mis-stây-mần"),
        ("tax compliance", "tax cờm-plai-ần-s"), ("depreciation", "đi-pri-si-ây-sần"),
        ("amortization", "a-mo-tai-zây-sần"), ("working capital", "uốc-king ca-pi-tồ"),
    ),
    "industry_product_project_operations": (
        ("Product Manager", "pro-đấc ma-ni-jờ"), ("Senior Product Manager", "si-ni-ờ pro-đấc ma-ni-jờ"),
        ("Associate Product Manager", "ờ-sô-si-ệt pro-đấc ma-ni-jờ"), ("Product Owner", "pro-đấc ô-nờ"),
        ("Chief Product Officer", "chíp pro-đấc óp-fi-sờ"), ("CPO", "xi-pi-ô"),
        ("Product Operations Manager", "pro-đấc óp-pờ-rây-sần ma-ni-jờ"),
        ("Project Manager", "pro-giẹc ma-ni-jờ"), ("Program Manager", "pro-grâm ma-ni-jờ"),
        ("Portfolio Manager", "pót-phô-li-ô ma-ni-jờ"), ("PMO Manager", "pi-em-ô ma-ni-jờ"),
        ("Project Coordinator", "pro-giẹc cô-o-đi-nây-tờ"), ("Scrum Master", "sờ-crầm má-stờ"),
        ("Agile Coach", "a-jai cô-ch"), ("Delivery Manager", "đi-li-vờ-ri ma-ni-jờ"),
        ("Operations Manager", "óp-pờ-rây-sần ma-ni-jờ"), ("Chief Operating Officer", "chíp óp-pờ-rây-ting óp-fi-sờ"),
        ("COO", "xi-ô-ô"), ("Business Operations", "bi-zờ-nịt óp-pờ-rây-sần"),
        ("Strategy Manager", "sờ-tra-tờ-gi ma-ni-jờ"), ("Strategy Consultant", "sờ-tra-tờ-gi cờn-sân-tần"),
        ("Management Consultant", "ma-ni-j-mần cờn-sân-tần"), ("Process Improvement Manager", "pro-ses im-pru-vờ-mần ma-ni-jờ"),
        ("Continuous Improvement Manager", "cờn-ti-niu-ợt im-pru-vờ-mần ma-ni-jờ"),
        ("Supply Chain Manager", "sờ-plai cheyn ma-ni-jờ"), ("Procurement Manager", "pro-kiu-mần ma-ni-jờ"),
        ("Purchasing Manager", "pơ-chờ-sing ma-ni-jờ"), ("Vendor Manager", "ven-đờ ma-ni-jờ"),
        ("Operations Analyst", "óp-pờ-rây-sần a-na-list"), ("Business Operations Analyst", "bi-zờ-nịt óp-pờ-rây-sần a-na-list"),
        ("Product Discovery", "pro-đấc đi-scờ-vờ-ri"), ("Product Strategy", "pro-đấc sờ-tra-tờ-gi"),
        ("product-market fit", "pro-đấc ma-kịt fit"), ("PMF", "pi-em-ép"),
        ("minimum viable product", "mi-ni-mầm vai-ờ-bồ pro-đấc"), ("MVP", "em vi pi"),
        ("north star metric", "nọt star me-trích"), ("product roadmap", "pro-đấc rô-đ-map"),
        ("feature prioritization", "phi-chờ prai-o-ri-tai-zây-sần"), ("impact effort matrix", "im-pact e-phọt may-trịch"),
        ("user story mapping", "du-zờ sto-ri ma-ping"), ("acceptance criteria", "ắc-xép-tần cri-ti-ri-a"),
        ("definition of done", "đe-fi-ni-sần ợp đần"), ("OKR", "ô kây a"), ("KPI", "kay pi ai"),
        ("SOP", "ét-ô-pi"), ("standard operating procedure", "stân-đờt óp-pờ-rây-ting prờ-si-giờ"),
        ("root cause analysis", "rut coz a-na-lí-sịt"), ("process mapping", "pro-ses ma-ping"),
        ("Lean", "lin"), ("Six Sigma", "sích-sig-ma"), ("Kaizen", "kai-zen"),
    ),
    "industry_education_training": (
        ("Teacher", "ti-chờ"), ("Lecturer", "lec-chờ-rờ"), ("Professor", "prờ-fe-sờ"),
        ("Teaching Assistant", "ti-ching ờ-sít-tần"), ("Tutor", "tiu-tờ"),
        ("Instructor", "in-sờ-trắc-tờ"), ("Trainer", "trây-nờ"), ("Academic Advisor", "a-kờ-đe-mịc ờd-vai-zờ"),
        ("School Counselor", "sờ-cun cao-nờ-sờ-lờ"), ("Instructional Designer", "in-sờ-trắc-sần-nồ đi-zai-nờ"),
        ("Curriculum Developer", "cờ-ri-kiu-lầm đi-ve-lóp-pờ"), ("Education Consultant", "e-đu-kây-sần cờn-sân-tần"),
        ("School Principal", "sờ-cun prin-si-pồ"), ("Head Teacher", "hed ti-chờ"),
        ("Dean", "đin"), ("Department Head", "đi-pát-mần hed"), ("Education Manager", "e-đu-kây-sần ma-ni-jờ"),
        ("Learning and Development Specialist", "lơ-ning en-đ đi-ve-lóp-mần spe-sờ-list"),
        ("E-learning Specialist", "i-lơ-ning spe-sờ-list"), ("Content Developer", "con-tent đi-ve-lóp-pờ"),
        ("Research Assistant", "ri-sơ-ch ờ-sít-tần"), ("Education Researcher", "e-đu-kây-sần ri-sơ-chờ"),
        ("teacher training", "ti-chờ trây-ning"), ("lesson plan", "le-sần plan"),
        ("learning objective", "lơ-ning ợp-giẹc-tịp"), ("learning outcome", "lơ-ning out-cầm"),
        ("assessment", "ờ-ses-mần"), ("formative assessment", "pho-mờ-tịp ờ-ses-mần"),
        ("summative assessment", "sâm-mờ-tịp ờ-ses-mần"), ("rubric", "ru-brịch"),
        ("classroom management", "clas-rum ma-ni-j-mần"), ("blended learning", "blen-địt lơ-ning"),
        ("distance learning", "đis-tần-s lơ-ning"), ("online learning", "on-lain lơ-ning"),
        ("e-learning", "i-lơ-ning"), ("learning management system", "lơ-ning ma-ni-j-mần sí-stầm"),
        ("LMS", "el-em-ét"), ("MOOC", "muk"), ("student engagement", "stiu-đần en-gâyj-mần"),
        ("student retention", "stiu-đần ri-ten-sần"), ("pedagogy", "pe-đờ-gô-gi"),
        ("andragogy", "an-đờ-gô-gi"), ("educational technology", "e-đu-kây-sần-nồ tek-nó-lờ-gi"),
    ),
    "industry_healthcare_pharma": (
        ("Doctor", "đóc-tờ"), ("Physician", "phi-zi-sần"), ("Surgeon", "sơ-jần"),
        ("Nurse", "nớt"), ("Nurse Practitioner", "nớt prác-ti-sần-nờ"), ("Pharmacist", "pha-mờ-sịt"),
        ("Pharmacy Technician", "pha-mờ-si tek-ni-sần"), ("Dentist", "đen-tịt"),
        ("Dental Assistant", "đen-tồ ờ-sít-tần"), ("Psychologist", "sai-có-lờ-jist"),
        ("Psychiatrist", "sai-cai-ờ-trist"), ("Physical Therapist", "phi-zi-cồ the-ra-pist"),
        ("Occupational Therapist", "óc-kiu-pây-sần-nồ the-ra-pist"), ("Radiologist", "rây-đi-ó-lờ-jist"),
        ("Radiology Technician", "rây-đi-ó-lờ-gi tek-ni-sần"), ("Laboratory Technician", "la-bờ-rờ-to-ri tek-ni-sần"),
        ("Medical Technologist", "me-đi-cồ tek-nó-lờ-jist"), ("Medical Doctor", "me-đi-cồ đóc-tờ"),
        ("Healthcare Administrator", "hel-th-ke a-đmi-ni-strây-tờ"), ("Hospital Administrator", "hó-spi-tồ a-đmi-ni-strây-tờ"),
        ("Healthcare Manager", "hel-th-ke ma-ni-jờ"), ("Clinical Researcher", "cli-ni-cồ ri-sơ-chờ"),
        ("Clinical Research Associate", "cli-ni-cồ ri-sơ-ch ờ-sô-si-ệt"),
        ("Clinical Trial Manager", "cli-ni-cồ trai-ồ ma-ni-jờ"), ("Medical Affairs Manager", "me-đi-cồ ờ-fe-z ma-ni-jờ"),
        ("Regulatory Affairs Specialist", "re-giu-lờ-to-ri ờ-fe-z spe-sờ-list"),
        ("Quality Control Analyst", "qua-li-ti cờn-trô a-na-list"), ("Quality Assurance Specialist", "qua-li-ti a-shu-rần spe-sờ-list"),
        ("Biostatistician", "bai-ô-stờ-ti-sti-sần"), ("Epidemiologist", "e-pi-đi-mi-ó-lờ-jist"),
        ("Public Health Specialist", "pắp-lic hel-th spe-sờ-list"), ("Nutritionist", "niu-tri-sần-nist"),
        ("Dietitian", "đai-ờ-ti-sần"), ("Care Coordinator", "ke co-o-đi-nây-tờ"),
        ("Medical Representative", "me-đi-cồ re-pri-zen-tờ-tịp"), ("Medical Sales Representative", "me-đi-cồ sâylz re-pri-zen-tịp"),
        ("Pharmaceutical Scientist", "pha-mờ-siu-ti-cồ sai-ần-tịt"), ("Pharmaceutical Engineer", "pha-mờ-siu-ti-cồ eng-gi-ni-ờ"),
        ("Clinical Pharmacist", "cli-ni-cồ pha-mờ-sịt"), ("Drug Safety Specialist", "drấg seif-ti spe-sờ-list"),
        ("pharmaceutical industry", "pha-mờ-siu-ti-cồ in-đờ-sờ-tri"), ("clinical trial", "cli-ni-cồ trai-ồ"),
        ("clinical research", "cli-ni-cồ ri-sơ-ch"), ("patient care", "pây-sần ke"),
        ("patient safety", "pây-sần seif-ti"), ("electronic health record", "i-lec-tron-nic hel-th re-cọt"),
        ("EHR", "i-ch a"), ("electronic medical record", "i-lec-tron-nic me-đi-cồ re-cọt"),
        ("EMR", "i-em-a"), ("HIPAA", "hip-a"), ("Good Manufacturing Practice", "gút ma-niu-phác-chờ-ring prác-tịt"),
        ("GMP", "gi-em-pi"), ("evidence-based medicine", "e-vi-đần-s bâyst me-đi-sần"),
        ("diagnosis", "đai-ạc-nô-sịt"), ("treatment plan", "trit-mần plan"), ("triage", "tri-a-ch"),
        ("infection control", "in-fec-sần cờn-trô"), ("informed consent", "in-pho-mịt cờn-sent"),
    ),
    "industry_law_legal": (
        ("Lawyer", "lo-ờ"), ("Attorney", "ờ-tơ-ni"), ("Solicitor", "sờ-li-si-tờ"),
        ("Barrister", "be-ri-stờ"), ("Legal Counsel", "li-gồ cao-n-sồ"),
        ("General Counsel", "je-nờ-rồ cao-n-sồ"), ("Corporate Counsel", "co-pờ-rịt cao-n-sồ"),
        ("Legal Advisor", "li-gồ ờd-vai-zờ"), ("Legal Assistant", "li-gồ ờ-sít-tần"),
        ("Paralegal", "pe-rờ-li-gồ"), ("Legal Secretary", "li-gồ se-crờ-te-ri"),
        ("Compliance Manager", "cờm-plai-ần-s ma-ni-jờ"), ("Compliance Analyst", "cờm-plai-ần-s a-na-list"),
        ("Contract Manager", "con-tract ma-ni-jờ"), ("Contract Specialist", "con-tract spe-sờ-list"),
        ("Litigation Lawyer", "li-ti-gây-sần lo-ờ"), ("Intellectual Property Lawyer", "in-tờ-lec-chu-ồ pro-pờ-ti lo-ờ"),
        ("IP Lawyer", "ai-pi lo-ờ"), ("Tax Lawyer", "tax lo-ờ"), ("Employment Lawyer", "em-ploi-mần lo-ờ"),
        ("Immigration Lawyer", "i-mi-grây-sần lo-ờ"), ("Criminal Lawyer", "cri-mi-nồ lo-ờ"),
        ("Judge", "giấj"), ("Prosecutor", "pro-si-kiu-tờ"), ("Legal Intern", "li-gồ in-tơn"),
        ("legal research", "li-gồ ri-sơ-ch"), ("legal advice", "li-gồ ờd-vais"),
        ("contract drafting", "con-tract dráp-ting"), ("contract negotiation", "con-tract ni-gô-si-ây-sần"),
        ("due diligence", "điu đi-li-jần-s"), ("dispute resolution", "đi-spiu-t re-zờ-lu-sần"),
        ("alternative dispute resolution", "ol-tơ-nờ-tịp đi-spiu-t re-zờ-lu-sần"), ("ADR", "ây-đi-a"),
        ("intellectual property", "in-tờ-lec-chu-ồ pro-pờ-ti"), ("copyright", "co-pi-rait"),
        ("trademark", "trây-đ-mak"), ("patent", "pây-tần"), ("trade secret", "trây-đ si-crit"),
        ("privacy law", "prai-vờ-si lo"), ("data protection", "đây-tờ prờ-tek-sần"),
        ("corporate governance", "co-pờ-rịt gơ-vờ-nần-s"), ("regulatory compliance", "re-giu-lờ-to-ri cờm-plai-ần-s"),
        ("anti-corruption", "an-ti cờ-rấp-sần"), ("anti-bribery", "an-ti brai-bờ-ri"),
        ("terms and conditions", "tơm-s en-đ cờn-đi-sần-s"), ("non-disclosure agreement", "non đi-scờ-lô-gi ờ-gri-mần"),
        ("NDA", "en đi ây"), ("service level agreement", "sơ-vịt le-vồ ờ-gri-mần"),
        ("power of attorney", "pao-ờ ợp ờ-tơ-ni"), ("memorandum of understanding", "me-mờ-ran-đầm ợp ân-đờ-stân-đing"),
        ("MOU", "em ô iu"), ("case law", "câys lo"), ("statute", "stát-chut"),
        ("precedent", "pre-si-đần"), ("jurisdiction", "giu-rít-đíc-sần"),
    ),
    "industry_construction_real_estate": (
        ("Civil Engineer", "si-vồ eng-gi-ni-ờ"), ("Structural Engineer", "sờ-trắc-chờ-rồ eng-gi-ni-ờ"),
        ("Mechanical Engineer", "mờ-can-ni-cồ eng-gi-ni-ờ"), ("Electrical Engineer", "i-lec-tri-cồ eng-gi-ni-ờ"),
        ("Construction Engineer", "cờn-strắc-sần eng-gi-ni-ờ"), ("Site Engineer", "sait eng-gi-ni-ờ"),
        ("Project Engineer", "pro-giẹc eng-gi-ni-ờ"), ("Construction Manager", "cờn-strắc-sần ma-ni-jờ"),
        ("Project Manager", "pro-giẹc ma-ni-jờ"), ("Site Manager", "sait ma-ni-jờ"),
        ("Construction Supervisor", "cờn-strắc-sần su-pờ-vai-zờ"), ("Site Supervisor", "sait su-pờ-vai-zờ"),
        ("Quantity Surveyor", "quan-ti-ti sơ-vây-ờ"), ("Cost Engineer", "cost eng-gi-ni-ờ"),
        ("Estimator", "es-ti-mây-tờ"), ("Architect", "a-ki-tek"), ("Landscape Architect", "land-scâyp a-ki-tek"),
        ("Urban Planner", "ơ-ban pla-nờ"), ("Building Inspector", "biu-đing in-spec-tờ"),
        ("Safety Officer", "seif-ti óp-fi-sờ"), ("HSE Manager", "ây-ch ét i ma-ni-jờ"),
        ("Health and Safety Engineer", "hel-th en-đ seif-ti eng-gi-ni-ờ"),
        ("Real Estate Agent", "ri-ồ i-stây-t ây-jần"), ("Real Estate Broker", "ri-ồ i-stây-t brô-cờ"),
        ("Property Manager", "pro-pờ-ti ma-ni-jờ"), ("Property Consultant", "pro-pờ-ti cờn-sân-tần"),
        ("Leasing Consultant", "li-sing cờn-sân-tần"), ("Real Estate Analyst", "ri-ồ i-stây-t a-na-list"),
        ("Real Estate Developer", "ri-ồ i-stây-t đi-ve-lóp-pờ"), ("Development Manager", "đi-ve-lóp-mần ma-ni-jờ"),
        ("Facilities Manager", "ờ-si-li-ti-s ma-ni-jờ"), ("Building Manager", "biu-đing ma-ni-jờ"),
        ("BIM Coordinator", "bi-em cô-o-đi-nây-tờ"), ("Building Information Modeling", "biu-đing in-phờ-mây-sần mo-đờ-ling"),
        ("BIM", "bi-em"), ("CAD", "ca-đ"), ("AutoCAD", "o-tô-ca-đ"), ("Revit", "re-vit"),
        ("blueprint", "blu-print"), ("floor plan", "flo plan"), ("bill of quantities", "bil ợp quan-ti-ti-s"),
        ("BOQ", "bi-ô-kiu"), ("bill of materials", "bil ợp mờ-ti-ri-ồ-s"), ("BOM", "bom"),
        ("critical path", "cri-ti-cồ path"), ("work breakdown structure", "uốc breyk-đao sờ-trắc-chờ"),
        ("WBS", "đắp-bồ-liu-bi-ét"), ("change order", "cheynj ó-đờ"), ("punch list", "pân-ch list"),
        ("occupational safety", "óc-kiu-pây-sần-nồ seif-ti"), ("site inspection", "sait in-spec-sần"),
    ),
    "industry_tourism_hospitality": (
        ("Hotel Manager", "hô-tel ma-ni-jờ"), ("General Manager", "je-nờ-rồ ma-ni-jờ"),
        ("Front Office Manager", "phờ-rân of-phít ma-ni-jờ"), ("Front Desk Agent", "phờ-rân desk ây-jần"),
        ("Receptionist", "ri-sep-sờ-nist"), ("Concierge", "con-si-ej"), ("Guest Relations Officer", "gest ri-lây-sần-s óp-fi-sờ"),
        ("Housekeeping Manager", "hao-s-ki-ping ma-ni-jờ"), ("Housekeeper", "hao-s-ki-pờ"),
        ("Executive Housekeeper", "ích-xe-kiu-tịp hao-s-ki-pờ"), ("Food and Beverage Manager", "phu-đ en-đ be-vờ-rịtj ma-ni-jờ"),
        ("F&B Manager", "ép en-đ bi ma-ni-jờ"), ("Restaurant Manager", "res-tờ-ran ma-ni-jờ"),
        ("Restaurant Supervisor", "res-tờ-ran su-pờ-vai-zờ"), ("Chef", "shef"), ("Head Chef", "hed shef"),
        ("Sous Chef", "su shef"), ("Pastry Chef", "pây-stri shef"), ("Bartender", "ba-ten-đờ"),
        ("Waiter", "uây-tờ"), ("Server", "sơ-vờ"), ("Event Coordinator", "i-ven cô-o-đi-nây-tờ"),
        ("Event Manager", "i-ven ma-ni-jờ"), ("Wedding Planner", "ue-đing pla-nờ"),
        ("Travel Consultant", "tra-vồ cờn-sân-tần"), ("Travel Agent", "tra-vồ ây-jần"),
        ("Tour Guide", "tuờ gai-đ"), ("Tour Operator", "tuờ óp-pờ-rây-tờ"), ("Travel Coordinator", "tra-vồ cô-o-đi-nây-tờ"),
        ("Destination Manager", "de-stờ-nây-sần ma-ni-jờ"), ("Revenue Manager", "re-vờ-niu ma-ni-jờ"),
        ("Revenue Management", "re-vờ-niu ma-ni-j-mần"), ("Yield Management", "yil ma-ni-j-mần"),
        ("occupancy rate", "óc-kiu-pần-si rât"), ("average daily rate", "a-vờ-rịt đâi-li rât"), ("ADR", "ây-đi-a"),
        ("revenue per available room", "re-vờ-niu pờ ờ-vây-lờ-bồ rum"), ("RevPAR", "rev-pa"),
        ("guest satisfaction", "gest sat-tịt-phác-sần"), ("guest experience", "gest ích-xpi-ri-ần-sờ"),
        ("service recovery", "sơ-vịt ri-cơ-vờ-ri"), ("food cost", "phu-đ cost"), ("menu engineering", "me-niu en-gi-ni-ờ-ring"),
        ("hospitality", "hó-spi-ta-li-ti"), ("tourism", "tuờ-riz-m"), ("sustainable tourism", "sờ-stây-nờ-bồ tuờ-riz-m"),
        ("OTA", "ô-ti-ây"), ("online travel agency", "on-lain tra-vồ ây-jần-si"),
    ),
    "industry_manufacturing_logistics_retail": (
        ("Manufacturing Engineer", "ma-niu-phác-chờ-ring eng-gi-ni-ờ"), ("Process Engineer", "pro-ses eng-gi-ni-ờ"),
        ("Production Engineer", "prờ-đắc-sần eng-gi-ni-ờ"), ("Industrial Engineer", "in-đờ-sờ-tri-ồ eng-gi-ni-ờ"),
        ("Automation Engineer", "o-tờ-mây-sần eng-gi-ni-ờ"), ("Robotics Engineer", "rô-bót-tịc eng-gi-ni-ờ"),
        ("Maintenance Engineer", "mâyn-tờ-nần-s eng-gi-ni-ờ"), ("Production Manager", "prờ-đắc-sần ma-ni-jờ"),
        ("Plant Manager", "plant ma-ni-jờ"), ("Factory Manager", "phác-tờ-ri ma-ni-jờ"),
        ("Quality Engineer", "qua-li-ti eng-gi-ni-ờ"), ("Quality Manager", "qua-li-ti ma-ni-jờ"),
        ("Lean Manufacturing", "lin ma-niu-phác-chờ-ring"), ("Six Sigma", "sích-sig-ma"),
        ("Supply Chain Analyst", "sờ-plai cheyn a-na-list"), ("Supply Chain Manager", "sờ-plai cheyn ma-ni-jờ"),
        ("Logistics Coordinator", "lờ-jis-tịc-s cô-o-đi-nây-tờ"), ("Logistics Manager", "lờ-jis-tịc-s ma-ni-jờ"),
        ("Warehouse Manager", "ue-hao-s ma-ni-jờ"), ("Warehouse Operator", "ue-hao-s óp-pờ-rây-tờ"),
        ("Inventory Manager", "in-vần-to-ri ma-ni-jờ"), ("Inventory Controller", "in-vần-to-ri cờn-trô-lờ"),
        ("Procurement Specialist", "pro-kiu-mần spe-sờ-list"), ("Purchasing Specialist", "pơ-chờ-sing spe-sờ-list"),
        ("Buyer", "bai-ờ"), ("Sourcing Specialist", "so-sing spe-sờ-list"), ("Demand Planner", "đi-man pla-nờ"),
        ("Supply Planner", "sờ-plai pla-nờ"), ("Merchandise Planner", "mơ-chần-đai-z pla-nờ"),
        ("Dispatch Coordinator", "đi-spách cô-o-đi-nây-tờ"), ("Fleet Manager", "flit ma-ni-jờ"),
        ("Driver", "drai-vờ"), ("Delivery Driver", "đi-li-vờ-ri drai-vờ"), ("Last Mile Delivery", "last mail đi-li-vờ-ri"),
        ("Retail Manager", "ri-tâyl ma-ni-jờ"), ("Store Manager", "sto ma-ni-jờ"),
        ("Retail Sales Associate", "ri-tâyl sâylz ờ-sô-si-ệt"), ("E-commerce Manager", "i-com-mơs ma-ni-jờ"),
        ("Merchandising Manager", "mơ-chần-đai-zing ma-ni-jờ"), ("Category Manager", "ca-tờ-gờ-ri ma-ni-jờ"),
        ("Visual Merchandiser", "vi-giu-ồ mơ-chần-đai-zờ"), ("Demand Forecasting", "đi-man pho-cát-ting"),
        ("inventory turnover", "in-vần-to-ri tơn-ô-vờ"), ("on-time delivery", "on taim đi-li-vờ-ri"),
        ("OTIF", "ô-ti-ép"), ("order fulfillment", "ó-đờ phul-phil-mần"),
        ("lead time", "li-đ taim"), ("safety stock", "seif-ti stóc"), ("warehouse management system", "ue-hao-s ma-ni-j-mần sí-stầm"),
        ("WMS", "đắp-bồ-liu-em-ét"), ("enterprise resource planning", "en-tờ-prai-z ri-só-sịt pla-ning"),
        ("ERP", "i-a-pi"), ("overall equipment effectiveness", "ô-vờ-ol i-qui-pmần i-phéc-tịp-nes"), ("OEE", "ô-i-i"),
    ),
    "industry_general": (
        ("Chief Executive Officer", "chíp ích-xe-kiu-tịp óp-fi-sờ"), ("CEO", "xi-i-ô"),
        ("Chief Operating Officer", "chíp óp-pờ-rây-ting óp-fi-sờ"), ("COO", "xi-ô-ô"),
        ("Chief Marketing Officer", "chíp ma-kịt-ting óp-fi-sờ"), ("CMO", "xi-em-ô"),
        ("Chief People Officer", "chíp pi-pồ óp-fi-sờ"), ("CPO", "xi-pi-ô"),
        ("Chief Executive", "chíp ích-xe-kiu-tịp"), ("Director", "đi-rec-tờ"),
        ("Manager", "ma-ni-jờ"), ("Senior Manager", "si-ni-ờ ma-ni-jờ"),
        ("Team Lead", "tim li-đ"), ("Team Leader", "tim li-đờ"), ("Supervisor", "su-pờ-vai-zờ"),
        ("Specialist", "spe-sờ-list"), ("Coordinator", "cô-o-đi-nây-tờ"),
        ("Consultant", "cờn-sân-tần"), ("Associate", "ờ-sô-si-ệt"), ("Executive", "ích-xe-kiu-tịp"),
        ("Intern", "in-tơn"), ("trainee", "trây-ni"), ("freelancer", "fri-lan-sờ"),
        ("contractor", "con-tract-tờ"), ("chief of staff", "chíp ợp stáp"),
        ("stakeholder management", "stâyk-hô-đờ ma-ni-j-mần"), ("cross-functional", "crót phâng-sần-nồ"),
        ("leadership", "li-đờ-ship"), ("mentoring", "men-tờ-ring"), ("coaching", "cô-ching"),
        ("decision-making", "đi-si-sần mây-king"), ("problem-solving", "pro-bờ-lầm sol-ving"),
        ("communication skills", "cờ-miu-ni-kây-sần skil-s"), ("stakeholder", "stâyk-hô-đờ"),
        ("key performance indicator", "ki pờ-pho-mần in-đi-kây-tờ"), ("KPI", "kay pi ai"),
        ("return on investment", "ri-tơn on in-vest-mần"), ("ROI", "a ô ai"),
        ("service level agreement", "sơ-vịt le-vồ ờ-gri-mần"), ("SLA", "ét-el-ây"),
        ("standard operating procedure", "stân-đờt óp-pờ-rây-ting prờ-si-giờ"), ("SOP", "ét-ô-pi"),
        ("full-time", "ful taim"), ("part-time", "pat taim"), ("remote work", "ri-mốt uốc"),
        ("hybrid work", "hai-brịt uốc"), ("work from home", "uốc from hô-m"),
        ("on-site", "on sait"), ("work-life balance", "uốc laip ba-lần-s"),
    ),
    "common_abbreviations": (
        ("as soon as possible", "az sun az pó-sờ-bồ"), ("FYI", "ép-uai-ai"),
        ("FAQ", "ép ây kiu"), ("ETA", "i-ti ây"), ("TBD", "ti bi đi"),
        ("TBC", "ti bi xi"), ("etc.", "i-tờ-cờ-ra"), ("versus", "vơ-sợt"),
        ("vs.", "vơ-sợt"), ("and so on", "en-đ sô on"), ("e.g.", "i-gi"),
        ("i.e.", "ai-i"), ("PO", "pi ô"), ("PR", "pi a"), ("3D", "thờ-ri đi"),
        ("2D", "tu đi"), ("24/7", "tu-en-ti pho se-vần"),
    ),
}


def _escaped_term(term: str) -> str:
    return re.escape(term).replace(r"\ ", r"\s+")


def _flatten_entries() -> tuple[PronunciationEntry, ...]:
    entries = [
        entry
        for pronunciation_set in PRONUNCIATION_SETS.values()
        for entry in pronunciation_set
    ]
    entries.sort(key=lambda item: len(item[0]), reverse=True)
    return tuple(entries)


PRONUNCIATION_ENTRIES = _flatten_entries()
PRONUNCIATION_RULES = tuple(
    (_escaped_term(term), pronunciation)
    for term, pronunciation in PRONUNCIATION_ENTRIES
)
_PRONUNCIATION_LOOKUP = {
    " ".join(term.split()).casefold(): pronunciation
    for term, pronunciation in PRONUNCIATION_ENTRIES
}
_PRONUNCIATION_PATTERN = re.compile(
    rf"(?<!\w)(?:{'|'.join(pattern for pattern, _ in PRONUNCIATION_RULES)})(?!\w)",
    re.IGNORECASE,
)


def apply_vbee_pronunciations(text: str) -> str:
    """Replace known technical terms with Vietnamese phonetic spellings."""

    def replace(match: re.Match[str]) -> str:
        key = " ".join(match.group(0).split()).casefold()
        return _PRONUNCIATION_LOOKUP[key]

    return _PRONUNCIATION_PATTERN.sub(replace, text)


def _clean_text(value: str) -> str:
    return " ".join(value.split()).strip()


def prepare_vbee_tts_text(display_text: str, generated_tts_text: str = "") -> str:
    """Prepare spoken text without changing the display question."""

    display = _clean_text(display_text)
    candidate = _clean_text(generated_tts_text)
    spoken = (
        candidate
        if candidate and len(candidate) >= max(20, int(len(display) * 0.6))
        else display
    )
    return apply_vbee_pronunciations(spoken)


def pronunciation_entry_count() -> int:
    return sum(len(pronunciation_set) for pronunciation_set in PRONUNCIATION_SETS.values())


def pronunciation_set_names() -> Iterable[str]:
    return PRONUNCIATION_SETS.keys()
